// Live aircraft positions from the community ADS-B network adsb.lol (Open Database License).
export const dynamic='force-dynamic';
const cache=new Map<string,{at:number;data:unknown}>();
export async function GET(req:Request){const u=new URL(req.url).searchParams,lat=Number(u.get('lat')),lon=Number(u.get('lon'));if(!Number.isFinite(lat)||!Number.isFinite(lon)||Math.abs(lat)>90||Math.abs(lon)>180)return Response.json({aircraft:[]},{status:400});
 const key=`${Math.round(lat*8)/8},${Math.round(lon*8)/8}`,hit=cache.get(key);if(hit&&Date.now()-hit.at<6000)return Response.json(hit.data);
 try{const res=await fetch(`https://api.adsb.lol/v2/point/${lat.toFixed(3)}/${lon.toFixed(3)}/40`,{headers:{'User-Agent':'hinode-world-flight/5 (browser flight game)'},signal:AbortSignal.timeout(7000)});if(!res.ok)throw new Error(`traffic ${res.status}`);const raw=await res.json();
  const aircraft=(raw.ac??[]).filter((a:any)=>Number.isFinite(a.lat)&&Number.isFinite(a.lon)&&(a.seen_pos??a.seen??99)<30&&!/^C/.test(String(a.category??''))&&!/^(TEST|GND|VEH|TUG|FOLLOW|FIRE)/i.test(String(a.flight??'').trim())).map((a:any)=>({hex:String(a.hex),flight:String(a.flight??'').trim(),reg:a.r??'',type:a.t??'',category:a.category??'',lat:a.lat,lon:a.lon,ground:a.alt_baro==='ground',alt:a.alt_baro==='ground'?null:Number(a.alt_geom??a.alt_baro)||null,gs:Number(a.gs)||0,track:Number(a.track??a.true_heading??a.mag_heading)||0,rate:Number(a.baro_rate??a.geom_rate)||0,squawk:a.squawk??'',age:Number(a.seen_pos??a.seen)||0})).slice(0,80);
  const data={aircraft,time:Date.now(),source:'adsb.lol'};cache.set(key,{at:Date.now(),data});if(cache.size>200)cache.delete(cache.keys().next().value!);return Response.json(data);}
 catch(e){return Response.json({aircraft:[],error:e instanceof Error?e.message:'Traffic unavailable'});}}
