import test from 'node:test';
import assert from 'node:assert/strict';
import {airportSearch,airports,createWorld,joinWorld,worldAction} from '../lib/worldFlightServer';
import {airportRunway,geoDistance,geoMove,geoBearing,nearRunway,worldSpawn,stepWorld,worldGuidance,type WorldInput} from '../lib/worldFlight';
const input:WorldInput={pitch:0,roll:0,rudder:0,throttle:1,brake:false,flaps:.5,trim:0,stability:true,gear:true,engine:true};
test('the worldwide catalog includes major airports, real runway thresholds and explicit estimated geometry',async()=>{const list=await airports();assert(list.length>70000);for(const id of ['RJTT','KJFK','EGLL','LFPG','VABB','VEIM','YSSY']){const a=(await airportSearch(id)).find(a=>a.id===id);assert(a);assert(Number.isFinite(a.lat)&&Number.isFinite(a.lon));const r=airportRunway(a);assert(r.length>500);assert(r.heading>=0&&r.heading<=360);}const jfk=(await airportSearch('KJFK'))[0],lhr=(await airportSearch('EGLL'))[0];assert(geoDistance(jfk,lhr)>5500000&&geoDistance(jfk,lhr)<5600000);const moved=geoMove(0,179.999,90,5000);assert(moved.lon<0);assert(Math.abs(geoDistance({lat:0,lon:179.999},moved)-5000)<.001);assert(Math.abs(geoBearing({lat:0,lon:179.999},moved)-90)<.01);});
test('runway roll and rotation cause an actual takeoff; fuel, stall and hard-contact recovery behave consistently',async()=>{const a=(await airportSearch('RJTT')).find(a=>a.id==='RJTT')!,p=worldSpawn(a);let takeoff=-1;for(let n=0;n<1400;n++){const i={...input,pitch:p.speed>31?.65:0};stepWorld(p,.05,i,a.elevation,nearRunway(p,[a]));if(!p.ground&&takeoff<0)takeoff=n*.05;}assert(takeoff>8&&takeoff<25,'takeoff must need a credible runway acceleration period');assert(!p.ground);assert(p.alt>a.elevation+80);assert(p.distance>1000);assert(p.fuel<100);const stalled={...p,speed:10,pitch:0};stepWorld(stalled,.05,{...input,throttle:0},a.elevation,null);assert(stalled.vertical<0);const crashed={...p,alt:a.elevation+1,pitch:-.3,vertical:-10};stepWorld(crashed,.05,input,a.elevation,null);assert.equal(crashed.phase,'HARD CONTACT · RECOVER');const pos={lat:crashed.lat,lon:crashed.lon};stepWorld(crashed,.05,input,a.elevation,null);assert.equal(geoDistance(pos,crashed),0);});
test('guidance completes a real approach, touches down inside the runway and brakes to a stop',async()=>{const a=(await airportSearch('RJAA')).find(a=>a.id==='RJAA')!,r=airportRunway(a),staging=geoMove(r.lat,r.lon,r.heading+180,4900),p={...worldSpawn(a),...staging,alt:a.elevation+245,heading:r.heading,pitch:0,speed:48,ground:false,airborne:true,engine:true};let final=true,landed=false;for(let n=0;n<16000;n++){const guide=worldGuidance(p,a,a,'approach',a.elevation,final);final=guide.final;stepWorld(p,.05,guide,a.elevation,nearRunway(p,[a]));assert.notEqual(p.phase,'HARD CONTACT · RECOVER');if(p.ground){landed=true;assert(nearRunway(p,[a]));if(p.speed<.1)break;}}assert(landed,'must land rather than circle forever');assert(p.speed<.1);assert(p.alt>a.elevation&&p.alt<a.elevation+3);});
test('two world pilots authenticate, share geographic movement, reconnect and recover independently',async()=>{const a=await createWorld('Aoi','RJTT','RJAA'),b=await joinWorld(a.room.code,'Ren');assert.deepEqual(b.room.names,['Aoi','Ren']);assert(!JSON.stringify(b.room).includes(a.token));await assert.rejects(()=>worldAction(a.room.code,'bad','get'),/Join/);await assert.rejects(()=>joinWorld(a.room.code,'Third'),/occupied/);const p={...a.room.planes[0],...geoMove(a.room.planes[0].lat,a.room.planes[0].lon,30,15),engine:true,throttle:.8};await worldAction(a.room.code,a.token,'move',p);const observed=await worldAction(a.room.code,b.token,'get');assert(geoDistance(observed.planes[0],p)<.001);assert.equal(observed.planes[0].engine,true);await assert.rejects(()=>worldAction(a.room.code,a.token,'move',{...p,lat:Infinity}),/Invalid/);const recovered=await worldAction(a.room.code,a.token,'recover');assert.equal(recovered.planes[0].recovery,1);assert.equal(recovered.planes[1].recovery,0);assert.equal(recovered.planes[0].speed,0);});
