import * as THREE from 'three';
import {headingDegrees,gps,groundDistance,stallSpeed,type Aircraft,type FlightPoint,type TerrainData} from '@/lib/flight';

// A camera-relative modeled cockpit, with instrument textures driven by flight state.
export function buildCockpit(){
 const group=new THREE.Group();group.name='Survey aircraft interior';group.position.set(0,.20,-.3);
 const charcoal=new THREE.MeshStandardMaterial({color:'#242b2f',roughness:.75,metalness:.3}),trim=new THREE.MeshStandardMaterial({color:'#c6c4b6',roughness:.5,metalness:.5}),black=new THREE.MeshStandardMaterial({color:'#121819',roughness:.4});
 const box=(w:number,h:number,d:number,x:number,y:number,z:number,m=charcoal)=>{const o=new THREE.Mesh(new THREE.BoxGeometry(w,h,d),m);o.position.set(x,y,z);group.add(o);return o;};
 const roundPanel=(w:number,h:number,d:number)=>{const s=new THREE.Shape(),r=.07;s.moveTo(-w/2+r,-h/2);s.lineTo(w/2-r,-h/2);s.quadraticCurveTo(w/2,-h/2,w/2,-h/2+r);s.lineTo(w/2,h/2-r);s.quadraticCurveTo(w/2,h/2,w/2-r,h/2);s.lineTo(-w/2+r,h/2);s.quadraticCurveTo(-w/2,h/2,-w/2,h/2-r);s.lineTo(-w/2,-h/2+r);s.quadraticCurveTo(-w/2,-h/2,-w/2+r,-h/2);return new THREE.ExtrudeGeometry(s,{depth:d,bevelEnabled:true,bevelSegments:3,steps:1,bevelSize:.018,bevelThickness:.012}).translate(0,0,-d/2);};
 const dashboard=new THREE.Mesh(roundPanel(2.6,.64,.24),charcoal);dashboard.position.set(0,-.83,-1.6);dashboard.rotation.x=-.12;group.add(dashboard);const lip=new THREE.Mesh(roundPanel(2.8,.08,.48),black);lip.position.set(0,-.51,-1.57);group.add(lip);
 // Lower pedestal, panel knobs and interior trim remain grounded to the airframe.
 box(.7,.6,.45,.85,-1.27,-1.6);for(let i=0;i<8;i++){const knob=new THREE.Mesh(new THREE.CylinderGeometry(.022,.027,.035,16),i%3===0?trim:black);knob.rotation.x=Math.PI/2;knob.position.set(-1.14+i*.18,-1.13,-1.38);group.add(knob);}for(const side of [-1,1]){box(.1,1.1,1.6,side*1.55,-.88,-.65,trim);box(.18,.08,1.55,side*1.49,-.36,-.65,black);}
 const lever=new THREE.Group();lever.position.set(.38,-1.13,-1.11);const shaft=new THREE.Mesh(new THREE.CylinderGeometry(.015,.015,.27,12),trim);shaft.position.y=.13;lever.add(shaft);const grip=new THREE.Mesh(new THREE.SphereGeometry(.05,16,12),black);grip.position.y=.28;lever.add(grip);group.add(lever);
 function brace(a:THREE.Vector3,b:THREE.Vector3,radius:number){const direction=b.clone().sub(a),o=new THREE.Mesh(new THREE.CylinderGeometry(radius,radius,direction.length(),12),trim);o.position.copy(a.clone().add(b).multiplyScalar(.5));o.quaternion.setFromUnitVectors(new THREE.Vector3(0,1,0),direction.normalize());group.add(o);}
 for(const s of [-1,1]){brace(new THREE.Vector3(s*1.4,-.5,-1.55),new THREE.Vector3(s*1.6,1.55,-2.7),.035);brace(new THREE.Vector3(s*.55,-.55,-1.8),new THREE.Vector3(s*.72,1.55,-2.7),.018);box(.05,.04,1.65,s*1.6,1.55,-1.9,trim);}box(3.2,.06,.05,0,1.55,-2.7,trim);
 // Interior fasteners and a rotating yoke add depth to the operational panel.
 for(const x of [-1.19,-.5,.5,1.19])for(const y of [-.59,-1.04]){const screw=new THREE.Mesh(new THREE.CylinderGeometry(.013,.013,.012,8),trim);screw.rotation.x=Math.PI/2;screw.position.set(x,y,-1.457);group.add(screw);}
 const yoke=new THREE.Group();yoke.position.set(0,-.96,-.91);const column=new THREE.Mesh(new THREE.CylinderGeometry(.026,.026,.35,12),charcoal);column.rotation.x=Math.PI/2;column.position.z=.11;yoke.add(column);const cross=new THREE.Mesh(new THREE.CylinderGeometry(.025,.025,.32,12),black);cross.rotation.z=Math.PI/2;yoke.add(cross);for(const side of [-1,1]){const grip=new THREE.Mesh(new THREE.CylinderGeometry(.033,.033,.15,12),black);grip.position.set(side*.16,.045,0);yoke.add(grip);}group.add(yoke);
 const canvas=document.createElement('canvas');canvas.width=2048;canvas.height=512;const ctx=canvas.getContext('2d')!;ctx.scale(2,2);const texture=new THREE.CanvasTexture(canvas);texture.colorSpace=THREE.SRGBColorSpace;
 const face=new THREE.Mesh(new THREE.PlaneGeometry(2.34,.585),new THREE.MeshBasicMaterial({map:texture}));face.position.set(0,0,.15);dashboard.add(face);
 function dial(x:number,label:string,value:number,max:number,unit:string){const y=124,r=65;ctx.fillStyle='#0b1115';ctx.beginPath();ctx.arc(x,y,r+5,0,Math.PI*2);ctx.fill();ctx.strokeStyle='#667777';ctx.lineWidth=3;ctx.stroke();ctx.save();ctx.translate(x,y);for(let i=0;i<=20;i++){const a=-Math.PI*.75+i/20*Math.PI*1.5;ctx.strokeStyle=i>16?'#ce6c5c':'#e4e4d4';ctx.lineWidth=i%2?1:2;ctx.beginPath();ctx.moveTo(Math.sin(a)*r*.78,-Math.cos(a)*r*.78);ctx.lineTo(Math.sin(a)*r*.9,-Math.cos(a)*r*.9);ctx.stroke();if(i%4===0){ctx.fillStyle='#c9d4cf';ctx.font='10px Arial';ctx.textAlign='center';ctx.fillText(String(Math.round(i/20*max)),Math.sin(a)*r*.59,-Math.cos(a)*r*.59+4);}}ctx.rotate(-Math.PI*.75+Math.min(1,Math.max(0,value/max))*Math.PI*1.5);ctx.fillStyle='#e9dec0';ctx.beginPath();ctx.moveTo(-3,8);ctx.lineTo(0,-r*.72);ctx.lineTo(3,8);ctx.fill();ctx.restore();ctx.fillStyle='#e2e9df';ctx.font='bold 12px Arial';ctx.textAlign='center';ctx.fillText(label,x,30);ctx.font='13px monospace';ctx.fillText(`${Math.round(value)} ${unit}`,x,220);}
 const navCanvas=document.createElement('canvas');navCanvas.width=512;navCanvas.height=256;const nc=navCanvas.getContext('2d')!,navTexture=new THREE.CanvasTexture(navCanvas);navTexture.colorSpace=THREE.SRGBColorSpace;const nav=new THREE.Mesh(new THREE.PlaneGeometry(.66,.33),new THREE.MeshBasicMaterial({map:navTexture}));nav.position.set(.85,-1.16,-1.364);group.add(nav);
 function update(p:Aircraft,agl:number,target:FlightPoint,t:TerrainData,navInfo?:{distance:number}){ctx.fillStyle='#1a2328';ctx.fillRect(0,0,1024,256);dial(90,'AIRSPEED',p.speed*1.944,220,'KT');dial(270,'ALTIMETER',p.y*3.28084,18000,'FT');dial(630,'ENGINE',900+p.throttle*2100,3500,'RPM');dial(810,'HEADING',headingDegrees(p.yaw),360,'°');
  ctx.save();ctx.translate(450,124);ctx.beginPath();ctx.arc(0,0,67,0,Math.PI*2);ctx.clip();ctx.rotate(p.roll);const horizon=p.pitch*120;ctx.fillStyle='#5894b3';ctx.fillRect(-110,-130,220,130+horizon);ctx.fillStyle='#8f7250';ctx.fillRect(-110,horizon,220,150);ctx.strokeStyle='#faf0d4';ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(-90,horizon);ctx.lineTo(90,horizon);ctx.stroke();for(let i=-3;i<=3;i++){ctx.beginPath();ctx.moveTo(-15,horizon+i*17);ctx.lineTo(15,horizon+i*17);ctx.stroke();}ctx.restore();ctx.strokeStyle='#e6e2c2';ctx.lineWidth=3;ctx.beginPath();ctx.moveTo(413,124);ctx.lineTo(438,124);ctx.lineTo(450,131);ctx.lineTo(462,124);ctx.lineTo(487,124);ctx.stroke();ctx.beginPath();ctx.arc(450,124,69,0,Math.PI*2);ctx.strokeStyle='#667777';ctx.stroke();ctx.fillStyle='#dce5df';ctx.font='bold 12px Arial';ctx.fillText('ATTITUDE',450,30);ctx.font='13px monospace';ctx.fillText(`${p.vertical>=0?'+':''}${(p.vertical*196.85).toFixed(0)} FT/M`,450,220);
  ctx.fillStyle='#273a40';ctx.fillRect(910,50,100,138);ctx.fillStyle='#8ddccb';ctx.font='12px monospace';ctx.textAlign='left';ctx.fillText('SURVEY',919,71);ctx.fillText('RAD ALT',919,102);ctx.font='bold 20px monospace';ctx.fillText(String(Math.round(agl*3.28084)),919,128);ctx.font='11px monospace';ctx.fillText('FT AGL',919,148);ctx.fillStyle=p.speed<stallSpeed(p)?'#ff7c56':'#e5d9ac';ctx.fillText(p.speed<stallSpeed(p)?'STALL':'FLIGHT',919,176);yoke.rotation.z=-p.roll*.45;yoke.position.y=-.96+p.pitch*.12;lever.rotation.x=.45-p.throttle*.8;texture.needsUpdate=true;
  nc.fillStyle='#07191e';nc.fillRect(0,0,512,256);nc.strokeStyle='#2c4d50';nc.lineWidth=1;for(let i=0;i<512;i+=32){nc.beginPath();nc.moveTo(i,0);nc.lineTo(i,256);nc.stroke();}for(let j=0;j<256;j+=32){nc.beginPath();nc.moveTo(0,j);nc.lineTo(512,j);nc.stroke();}nc.fillStyle='#81d8c7';nc.font='16px monospace';nc.fillText('HINODE NAV / GPS',15,25);const pos=gps(t,p);nc.fillText(`${pos.lat.toFixed(4)} N  ${pos.lon.toFixed(4)} E`,15,229);nc.strokeStyle='#e5c788';nc.setLineDash([7,6]);nc.beginPath();nc.moveTo(110,134);const bearing=Math.atan2(target.x-p.x,target.z-p.z);nc.lineTo(110+Math.sin(bearing)*85,134+Math.cos(bearing)*85);nc.stroke();nc.setLineDash([]);nc.save();nc.translate(110,134);nc.rotate(p.yaw);nc.fillStyle='#e8e4cd';nc.beginPath();nc.moveTo(0,-12);nc.lineTo(7,9);nc.lineTo(0,5);nc.lineTo(-7,9);nc.fill();nc.restore();nc.fillStyle='#e3d9b8';nc.font='bold 20px monospace';nc.fillText(`${((navInfo?.distance??groundDistance(p,target))/1000).toFixed(1)} KM`,290,88);nc.font='15px monospace';nc.fillText(`FLAPS ${Math.round((p.flaps??0)*30)}°`,290,120);nc.fillText(`THR ${Math.round(p.throttle*100)}%`,290,147);navTexture.needsUpdate=true;
 }
 return{group,update};
}
