import * as THREE from 'three';
import {mergeGeometries} from 'three/examples/jsm/utils/BufferGeometryUtils.js';
import {terrainHeight,type TerrainData} from '@/lib/flight';

export type SceneryData={buildings:{id:number;p:number[][];h:number;estimated:boolean}[];forests:number[][][];lakes:number[][][]};
export const polygonArea=(p:number[][])=>Math.abs(p.reduce((a,q,i)=>a+q[0]*p[(i+1)%p.length][1]-p[(i+1)%p.length][0]*q[1],0)/2);
export function contains(p:number[][],x:number,z:number){let inside=false;for(let i=0,j=p.length-1;i<p.length;j=i++){const a=p[i],b=p[j];if((a[1]>z)!==(b[1]>z)&&x<(b[0]-a[0])*(z-a[1])/(b[1]-a[1])+a[0])inside=!inside;}return inside;}
export function geographicShape(points:number[][]){const shape=new THREE.Shape();points.forEach(([x,z],i)=>i?shape.lineTo(x,-z):shape.moveTo(x,-z));shape.closePath();return shape;}
function colorGeometry(g:THREE.BufferGeometry,color:THREE.Color){const a=g.getAttribute('position'),c=new Float32Array(a.count*3);for(let i=0;i<a.count;i++)color.toArray(c,i*3);g.setAttribute('color',new THREE.BufferAttribute(c,3));return g;}

// Actual OSM footprints; missing heights use the openly labeled level estimate.
// Forest positions are procedural samples inside mapped forest boundaries.
export function buildGeographicScenery(t:TerrainData,data:SceneryData){
 const group=new THREE.Group();group.name='OpenStreetMap buildings and mapped forests';const walls:number[]=[],wallNormals:number[]=[],wallUv:number[]=[],roof:number[]=[],roofNormals:number[]=[],roofColors:number[]=[];
 const wallCanvas=document.createElement('canvas');wallCanvas.width=wallCanvas.height=128;const ctx=wallCanvas.getContext('2d')!;ctx.fillStyle='#b1ada0';ctx.fillRect(0,0,128,128);ctx.fillStyle='#9f9d91';ctx.fillRect(0,120,128,8);ctx.fillStyle='#394c50';ctx.fillRect(24,25,78,65);ctx.fillStyle='#6b7b7c';ctx.fillRect(28,29,70,6);ctx.fillStyle='#abb6ad';ctx.fillRect(61,27,3,62);ctx.fillRect(25,55,75,3);const wallTexture=new THREE.CanvasTexture(wallCanvas);wallTexture.colorSpace=THREE.SRGBColorSpace;wallTexture.wrapS=wallTexture.wrapT=THREE.RepeatWrapping;wallTexture.repeat.set(.35,.28);
 let houses=0;for(const b of data.buildings){const x=b.p.reduce((a,p)=>a+p[0],0)/b.p.length,z=b.p.reduce((a,p)=>a+p[1],0)/b.p.length,heights=b.p.map(p=>terrainHeight(t,p[0],p[1]));if(Math.max(...heights)-Math.min(...heights)>12)continue;const base=terrainHeight(t,x,z)-2,geo=new THREE.ExtrudeGeometry(geographicShape(b.p),{depth:b.h+2,bevelEnabled:false,steps:1});geo.rotateX(-Math.PI/2);geo.translate(0,base,0);const p=geo.getAttribute('position'),n=geo.getAttribute('normal'),uv=geo.getAttribute('uv'),c=new THREE.Color(['#68716e','#8a8070','#5d666c','#716c64'][b.id%4]);for(let i=0;i<p.count;i++){if(n.getY(i)<-.5)continue;if(n.getY(i)>.5){roof.push(p.getX(i),p.getY(i),p.getZ(i));roofNormals.push(n.getX(i),n.getY(i),n.getZ(i));c.toArray(roofColors,roofColors.length);}else{walls.push(p.getX(i),p.getY(i),p.getZ(i));wallNormals.push(n.getX(i),n.getY(i),n.getZ(i));wallUv.push(uv.getX(i),uv.getY(i));}}geo.dispose();houses++;}
 if(houses){const g=new THREE.BufferGeometry();g.setAttribute('position',new THREE.Float32BufferAttribute(walls,3));g.setAttribute('normal',new THREE.Float32BufferAttribute(wallNormals,3));g.setAttribute('uv',new THREE.Float32BufferAttribute(wallUv,2));const m=new THREE.Mesh(g,new THREE.MeshStandardMaterial({map:wallTexture,roughness:.95}));m.name='Geographic building walls';group.add(m);const r=new THREE.BufferGeometry();r.setAttribute('position',new THREE.Float32BufferAttribute(roof,3));r.setAttribute('normal',new THREE.Float32BufferAttribute(roofNormals,3));r.setAttribute('color',new THREE.Float32BufferAttribute(roofColors,3));group.add(new THREE.Mesh(r,new THREE.MeshStandardMaterial({vertexColors:true,roughness:1})));}else wallTexture.dispose();
 const forests=data.forests.map(p=>({p,minX:Math.min(...p.map(q=>q[0])),maxX:Math.max(...p.map(q=>q[0])),minZ:Math.min(...p.map(q=>q[1])),maxZ:Math.max(...p.map(q=>q[1]))})),positions:number[][]=[];
 let seed=t.id.split('').reduce((a,c)=>a+c.charCodeAt(0),1);const random=()=>{seed=(seed*1664525+1013904223)>>>0;return seed/4294967296;};
 for(let z=30;z<t.size;z+=65)for(let x=30;x<t.size;x+=65){const px=x+(random()-.5)*52,pz=z+(random()-.5)*52,y=terrainHeight(t,px,pz);if(y<2||y>2450)continue;if(forests.some(f=>px>f.minX&&px<f.maxX&&pz>f.minZ&&pz<f.maxZ&&contains(f.p,px,pz)))positions.push([px,y,pz,10+random()*13,random()*6.28]);}
 const trunk=colorGeometry(new THREE.CylinderGeometry(.025,.045,.6,5).translate(0,.3,0).toNonIndexed(),new THREE.Color('#5a5141')),parts=[trunk];for(let i=0;i<3;i++){const g=new THREE.ConeGeometry(.23-i*.035,.55,7).translate(0,.57+i*.15,0).toNonIndexed();parts.push(colorGeometry(g,new THREE.Color(i%2?'#3e5748':'#4d6451')));}const treeGeo=mergeGeometries(parts)!;parts.forEach(g=>g.dispose());
 const treeMaterial=new THREE.MeshStandardMaterial({vertexColors:true,roughness:1}),wind={value:0};treeMaterial.onBeforeCompile=shader=>{shader.uniforms.treeTime=wind;shader.vertexShader='uniform float treeTime;\n'+shader.vertexShader;shader.vertexShader=shader.vertexShader.replace('#include <begin_vertex>','#include <begin_vertex>\n transformed.x += sin(treeTime*1.2+instanceMatrix[3].x*.015+instanceMatrix[3].z*.02)*.015*smoothstep(.3,1.0,position.y);');};
 const trees=new THREE.InstancedMesh(treeGeo,treeMaterial,positions.length),dummy=new THREE.Object3D(),col=new THREE.Color();positions.forEach(([x,y,z,h,a],i)=>{dummy.position.set(x,y,z);dummy.scale.set(h,h,h);dummy.rotation.y=a;dummy.updateMatrix();trees.setMatrixAt(i,dummy.matrix);trees.setColorAt(i,col.setHSL(.29+random()*.08,.12+random()*.08,.7+random()*.2));});trees.instanceMatrix.needsUpdate=true;trees.computeBoundingSphere();trees.name='Wind animated forest';group.add(trees);
 return{group,houses,trees:positions.length,update:(time:number)=>{wind.value=time;}};
}
