'use client';
import {useEffect,useRef,useState} from 'react';
import type * as Cesium from 'cesium';
import * as THREE from 'three';
import {buildCockpit} from './FlightCockpit';
import {disposeWorld} from './FlightWorld';
import {FlightAudio} from '@/lib/flightAudio';
import {openTerrain,worldImagery,groundAt} from '@/lib/worldTerrain';
import {airportRunway,geoMove,geoDistance,geoBearing,nearRunway,stepWorld,worldGuidance,worldStallSpeed,type WorldRoom,type WorldPlane,type WorldInput} from '@/lib/worldFlight';
import {clamp,type Aircraft,type TerrainData} from '@/lib/flight';

declare global{interface Window{Cesium:typeof Cesium;CESIUM_BASE_URL:string;}}
let cesiumLoading:Promise<typeof Cesium>|undefined;
function loadCesium(){return cesiumLoading??=new Promise((resolve,reject)=>{if(window.Cesium)return resolve(window.Cesium);window.CESIUM_BASE_URL='/cesium/';const s=document.createElement('script');s.src='/cesium/Cesium.js';s.onload=()=>resolve(window.Cesium);s.onerror=()=>reject(new Error('The globe engine could not load.'));document.head.appendChild(s);});}
export type WorldControls=WorldInput&{camera:number;clean:boolean;daylight:boolean;guidance:'off'|'departure'|'approach'};
export type WorldTelemetry={plane:WorldPlane;agl:number;remaining:number;bearing:number;elapsed:number;terrainReady:boolean};
type Props={room:WorldRoom|null;controls:WorldControls;sound:boolean;paused:boolean;onMove:(p:WorldPlane)=>void;onTelemetry:(t:WorldTelemetry)=>void;onError:(s:string)=>void};

export default function WorldCanvas(props:Props){
 const mount=useRef<HTMLDivElement>(null),cockpitMount=useRef<HTMLDivElement>(null),live=useRef(props);live.current=props;const [loading,setLoading]=useState(true);
 useEffect(()=>{
  let dead=false,viewer:Cesium.Viewer|undefined,frame=0,audio:FlightAudio|undefined,renderer:THREE.WebGLRenderer|undefined,cockpitScene:THREE.Scene|undefined;const keys=new Set<string>(),look={yaw:0,pitch:0};let drag=false,lastPointer=[0,0];
  const keydown=(e:KeyboardEvent)=>{if((e.target as HTMLElement)?.matches('input,select,textarea'))return;if(['Space','ArrowUp','ArrowDown','ArrowLeft','ArrowRight'].includes(e.code))e.preventDefault();keys.add(e.code);if(e.code==='Home')look.yaw=look.pitch=0;},keyup=(e:KeyboardEvent)=>keys.delete(e.code),blur=()=>{keys.clear();drag=false;};window.addEventListener('keydown',keydown);window.addEventListener('keyup',keyup);window.addEventListener('blur',blur);
  const pointerDown=(e:PointerEvent)=>{if(live.current.controls.camera!==1||e.button!==0)return;drag=true;lastPointer=[e.clientX,e.clientY];mount.current?.setPointerCapture(e.pointerId);},pointerMove=(e:PointerEvent)=>{if(!drag)return;look.yaw=clamp(look.yaw+(e.clientX-lastPointer[0])*.16,-85,85);look.pitch=clamp(look.pitch-(e.clientY-lastPointer[1])*.13,-25,40);lastPointer=[e.clientX,e.clientY];},pointerUp=()=>{drag=false;};const el=mount.current;el?.addEventListener('pointerdown',pointerDown);el?.addEventListener('pointermove',pointerMove);el?.addEventListener('pointerup',pointerUp);el?.addEventListener('pointercancel',pointerUp);
  async function init(){try{
   setLoading(true);const C=await loadCesium();if(dead||!mount.current)return;const terrain=openTerrain(C);viewer=new C.Viewer(mount.current,{terrainProvider:terrain,baseLayer:new C.ImageryLayer(worldImagery(C)),animation:false,timeline:false,geocoder:false,homeButton:false,sceneModePicker:false,baseLayerPicker:false,navigationHelpButton:false,fullscreenButton:false,selectionIndicator:false,infoBox:false,shouldAnimate:true,shadows:false,contextOptions:{webgl:{alpha:false,antialias:true}},msaaSamples:2});
   const v=viewer;v.resolutionScale=Math.min(1,window.devicePixelRatio>1?.85:1);v.scene.globe.maximumScreenSpaceError=3;v.scene.globe.tileCacheSize=100;v.scene.globe.depthTestAgainstTerrain=true;v.scene.globe.enableLighting=true;v.scene.fog.enabled=true;v.scene.highDynamicRange=true;v.clock.multiplier=1;v.scene.screenSpaceCameraController.enableInputs=false;
   v.imageryLayers.addImageryProvider(new C.UrlTemplateImageryProvider({url:'https://cyberjapandata.gsi.go.jp/xyz/seamlessphoto/{z}/{x}/{y}.jpg',rectangle:C.Rectangle.fromDegrees(129,30,146,46),minimumLevel:5,maximumLevel:17,credit:new C.Credit('<a href="https://www.gsi.go.jp/kikakuchousei/kikakuchousei40182.html">GSI Japan imagery / Landsat8 / USGS / GEBCO</a>')}));
   const room=live.current.room;if(!room){v.camera.setView({destination:C.Cartesian3.fromDegrees(138.7,35.5,180000),orientation:{heading:0,pitch:-.9,roll:0}});setLoading(false);return;}
   const craft=await C.Model.fromGltfAsync({url:'/flight/models/Cesium_Air.glb',modelMatrix:C.Matrix4.IDENTITY,scale:1,minimumPixelSize:0,maximumScale:1});if(dead){craft.destroy();return;}v.scene.primitives.add(craft);
   const remote=await C.Model.fromGltfAsync({url:'/flight/models/Cesium_Air.glb',modelMatrix:C.Matrix4.IDENTITY,scale:1,color:C.Color.fromCssColorString('#8fceee'),colorBlendMode:C.ColorBlendMode.MIX,colorBlendAmount:.35});if(dead){remote.destroy();return;}v.scene.primitives.add(remote);
   const airports=[room.departure,room.arrival];for(const airport of airports){const rw=airportRunway(airport),rways=airport.runways.length?airport.runways:[rw];for(const r of rways.slice(0,5)){
    const half=Math.max(15,r.width/2),a=geoMove(r.lat,r.lon,r.heading-90,half),b=geoMove(r.lat,r.lon,r.heading+90,half),c=geoMove(r.endLat,r.endLon,r.heading+90,half),d=geoMove(r.endLat,r.endLon,r.heading-90,half);
    v.entities.add({name:`${airport.id} ${r.name}`,polygon:{hierarchy:C.Cartesian3.fromDegreesArray([a.lon,a.lat,b.lon,b.lat,c.lon,c.lat,d.lon,d.lat]),height:airport.elevation+.4,material:C.Color.fromCssColorString('#424b4e'),outline:false}});
    const centerline=[];for(let dist=120;dist<r.length-100;dist+=90){const a=geoMove(r.lat,r.lon,r.heading,dist),b=geoMove(r.lat,r.lon,r.heading,dist+35);centerline.push(v.entities.add({polyline:{positions:C.Cartesian3.fromDegreesArrayHeights([a.lon,a.lat,airport.elevation+.65,b.lon,b.lat,airport.elevation+.65]),width:3,material:C.Color.WHITE}}));}
    for(let dist=0;dist<r.length;dist+=90)for(const side of [-1,1]){const point=geoMove(r.lat,r.lon,r.heading,dist),edge=geoMove(point.lat,point.lon,r.heading+side*90,half+2);v.entities.add({position:C.Cartesian3.fromDegrees(edge.lon,edge.lat,airport.elevation+1),point:{pixelSize:3,color:C.Color.fromCssColorString('#f7eed2'),disableDepthTestDistance:2000}});}
   }
   v.entities.add({position:C.Cartesian3.fromDegrees(airport.lon,airport.lat,airport.elevation+70),label:{text:`${airport.id} · ${airport.name}`,font:'13px sans-serif',fillColor:C.Color.WHITE,style:C.LabelStyle.FILL_AND_OUTLINE,outlineColor:C.Color.BLACK,outlineWidth:2,scale:.8,distanceDisplayCondition:new C.DistanceDisplayCondition(500,60000)}});}
   // Cockpit is a separate original modeled interior; no aircraft vendor assets.
   const cockpit=buildCockpit();cockpitScene=new THREE.Scene();cockpitScene.add(cockpit.group,new THREE.HemisphereLight('#d9e6ed','#475860',2.2));const key=new THREE.DirectionalLight('#f2e2c2',2);key.position.set(-2,3,2);cockpitScene.add(key);const camera=new THREE.PerspectiveCamera(68,1,.05,40);renderer=new THREE.WebGLRenderer({alpha:true,antialias:true});renderer.setPixelRatio(Math.min(1.4,devicePixelRatio));renderer.setClearColor(0,0);renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=.8;cockpitMount.current?.appendChild(renderer.domElement);
   let plane={...room.planes[room.seat]},recovery=plane.recovery,last=performance.now(),send=0,telemetry=0,elapsed=0,ground=room.departure.elevation,groundReady=false,groundRequest=0,throttle=plane.throttle,lastThrottle=props.controls.throttle,lastDaylight: boolean|undefined,terrainNotice=false,finalApproach=false,lastGuidance='off',craftSpinning=false,remoteSpinning=false;
   const terrainT={id:'global',name:'Earth',north:90,south:-90,west:-180,east:180,size:360,grid:2,heights:[0,0,0,0],lat:0,lon:0} as TerrainData;
   setLoading(false);
   const render=(now:number)=>{if(dead||!viewer||!renderer||!cockpitScene)return;frame=requestAnimationFrame(render);const p=live.current,r=p.room;if(!r)return;const dt=Math.min(1,(now-last)/1000);last=now;
    if(r.planes[r.seat].recovery!==recovery){plane={...r.planes[r.seat]};recovery=plane.recovery;throttle=0;ground=r.departure.elevation;look.yaw=look.pitch=0;finalApproach=false;}
    const carto=C.Cartographic.fromDegrees(plane.lon,plane.lat),height=v.scene.globe.getHeight(carto);if(height!==undefined){ground=height;groundReady=true;}if(now-groundRequest>2000){groundRequest=now;void groundAt(plane.lat,plane.lon).then(h=>{if(!dead){ground=h;groundReady=true;}}).catch(()=>{if(!terrainNotice){p.onError('Some terrain tiles are unavailable. Scenery will retry; avoid low flight until terrain loads.');terrainNotice=true;}});}
    const pad=navigator.getGamepads?.().find(g=>g?.connected),axis=(i:number)=>pad&&Math.abs(pad.axes[i]??0)>.12?pad.axes[i]:0;
    if(lastThrottle!==p.controls.throttle){throttle=p.controls.throttle;lastThrottle=p.controls.throttle;}if(!p.paused&&!document.hidden){elapsed+=dt;throttle=clamp(throttle+dt*((keys.has('KeyE')?.18:0)-(keys.has('KeyQ')?.18:0)+(pad?.buttons[7]?.value??0)*.2-(pad?.buttons[6]?.value??0)*.2),0,1);let input={...p.controls,throttle,pitch:clamp(p.controls.pitch+(keys.has('KeyS')||keys.has('ArrowDown')?1:0)-(keys.has('KeyW')||keys.has('ArrowUp')?1:0)+axis(1),-1,1),roll:clamp(p.controls.roll+(keys.has('KeyD')||keys.has('ArrowRight')?1:0)-(keys.has('KeyA')||keys.has('ArrowLeft')?1:0)+axis(0),-1,1),rudder:(keys.has('KeyX')?1:0)-(keys.has('KeyZ')?1:0)+p.controls.rudder,brake:p.controls.brake||keys.has('Space')||!!pad?.buttons[1]?.pressed};if(lastGuidance!==p.controls.guidance){finalApproach=false;lastGuidance=p.controls.guidance;}if(p.controls.guidance!=='off'){const assisted=worldGuidance(plane,r.departure,r.arrival,p.controls.guidance,ground,finalApproach);finalApproach=assisted.final;input={...input,...assisted,pitch:input.pitch||assisted.pitch,roll:input.roll||assisted.roll,rudder:input.rudder||assisted.rudder};}let remaining=dt;while(remaining>0){const slice=Math.min(.05,remaining);stepWorld(plane,slice,input,ground,nearRunway(plane,airports));remaining-=slice;}look.yaw=clamp(look.yaw+axis(2)*dt*35,-85,85);look.pitch=clamp(look.pitch-axis(3)*dt*25,-25,40);}
    if(lastDaylight!==p.controls.daylight){lastDaylight=p.controls.daylight;const date=new Date();if(p.controls.daylight){date.setUTCHours(12-Math.round(plane.lon/15),0,0,0);}v.clock.currentTime=C.JulianDate.fromDate(date);}
    const position=C.Cartesian3.fromDegrees(plane.lon,plane.lat,plane.alt),hpr=new C.HeadingPitchRoll(C.Math.toRadians(plane.heading-90),plane.pitch,-plane.roll);craft.modelMatrix=C.Transforms.headingPitchRollToFixedFrame(position,hpr);craft.show=p.controls.camera!==1;if(craft.ready&&craftSpinning!==plane.engine){craftSpinning=plane.engine;craft.activeAnimations.removeAll();if(plane.engine)craft.activeAnimations.addAll({loop:C.ModelAnimationLoop.REPEAT});}
    const other=r.planes[1-r.seat];if(remote.ready&&remoteSpinning!==other.engine){remoteSpinning=other.engine;remote.activeAnimations.removeAll();if(other.engine)remote.activeAnimations.addAll({loop:C.ModelAnimationLoop.REPEAT});}remote.show=!!r.names[1]&&Date.now()-other.seen<6000;remote.modelMatrix=C.Transforms.headingPitchRollToFixedFrame(C.Cartesian3.fromDegrees(other.lon,other.lat,other.alt),new C.HeadingPitchRoll(C.Math.toRadians(other.heading-90),other.pitch,-other.roll));
    v.camera.lookAtTransform(C.Matrix4.IDENTITY);if(p.controls.camera===1){v.camera.setView({destination:C.Cartesian3.fromDegrees(plane.lon,plane.lat,plane.alt+1.5),orientation:{heading:C.Math.toRadians(plane.heading+look.yaw),pitch:plane.pitch+C.Math.toRadians(look.pitch),roll:-plane.roll}});}else{v.camera.lookAtTransform(C.Transforms.eastNorthUpToFixedFrame(position),new C.HeadingPitchRange(C.Math.toRadians(p.controls.camera===2?plane.heading+70:plane.heading),p.controls.camera===2?-.4:-.16,p.controls.camera===2?160:65));}
    const host=mount.current!,size=host.getBoundingClientRect();if(renderer.domElement.width!==Math.round(size.width*renderer.getPixelRatio())||renderer.domElement.height!==Math.round(size.height*renderer.getPixelRatio())){renderer.setSize(size.width,size.height);camera.aspect=size.width/size.height;camera.updateProjectionMatrix();cockpit.group.scale.x=Math.min(1,camera.aspect/.9);}camera.rotation.set(C.Math.toRadians(look.pitch),-C.Math.toRadians(look.yaw),0,'YXZ');cockpitMount.current!.style.display=p.controls.camera===1?'block':'none';
    if(now-telemetry>150){const agl=plane.alt-(nearRunway(plane,airports)?nearRunway(plane,airports)!.airport.elevation:ground),distance=geoDistance(plane,r.arrival);p.onTelemetry({plane:{...plane},agl,remaining:distance,bearing:geoBearing(plane,r.arrival),elapsed,terrainReady:groundReady});const fake:Aircraft={x:plane.lon+180,z:(90-plane.lat)*2,y:plane.alt,yaw:C.Math.toRadians(plane.heading),pitch:plane.pitch,roll:plane.roll,speed:plane.speed,throttle:plane.throttle,vertical:plane.vertical,flaps:plane.flaps,seen:plane.seen,recovery:plane.recovery,landed:plane.ground};cockpit.update(fake,agl,{x:r.arrival.lon+180,z:(90-r.arrival.lat)*2,y:r.arrival.elevation},terrainT,{distance});telemetry=now;}
    if(p.controls.camera===1)renderer.render(cockpitScene,camera);if(p.sound&&!p.paused&&!document.hidden&&(plane.engine||plane.speed>10)){audio??=new FlightAudio();audio.update(plane.engine?plane.throttle:0,plane.speed,p.controls.camera===1,!plane.ground&&plane.speed<worldStallSpeed(plane),plane.ground?1000:plane.alt-ground);}else{audio?.dispose();audio=undefined;}if(now-send>500&&!p.paused){p.onMove({...plane});send=now;}
   };frame=requestAnimationFrame(render);
  }catch(e){if(!dead){setLoading(false);live.current.onError(e instanceof Error?e.message:'Globe could not start.');}}}
  void init();return()=>{dead=true;cancelAnimationFrame(frame);window.removeEventListener('keydown',keydown);window.removeEventListener('keyup',keyup);window.removeEventListener('blur',blur);el?.removeEventListener('pointerdown',pointerDown);el?.removeEventListener('pointermove',pointerMove);el?.removeEventListener('pointerup',pointerUp);el?.removeEventListener('pointercancel',pointerUp);audio?.dispose();if(viewer&&!viewer.isDestroyed())viewer.destroy();if(cockpitScene)disposeWorld(cockpitScene);renderer?.dispose();renderer?.domElement.remove();};
 },[props.room?.code]);
 return <><div className="world-globe" ref={mount}/><div className="world-cockpit" ref={cockpitMount}/>{loading&&<div className="world-loading"><span className="load-ring"/><h2>Preparing your world</h2><p>Loading globe, terrain and aircraft…</p></div>}</>;
}
