'use client';
import {useEffect,useRef,useState} from 'react';
import type * as Cesium from 'cesium';
import * as THREE from 'three';
import {buildCockpit} from './FlightCockpit';
import {disposeWorld} from './FlightWorld';
import {drawPanel,type AvionicsData,type NavPoint} from './Avionics';
import {aircraftModelUrl,MODEL_GROUND} from './AircraftModels';
import {AirfieldLayer,CloudField,AircraftLights,TrafficLayer,weatherStage,sunElevation,type LiveTraffic} from './worldScene';
import type {Sim,Telemetry,TimePreset} from './sim';
import {AircraftAudio,Speaker} from '@/lib/aircraftAudio';
import {openTerrain,worldImagery,sentinelImagery,regionalImagery,nightImagery,groundInfo,flattenAirport} from '@/lib/worldTerrain';
import {geoDistance,geoBearing,geoMove,nearRunway,stepWorld,worldStallSpeed,type Airport,type WorldRoom,type WorldPlane} from '@/lib/worldFlight';
import {spec,vSpeeds,aircraftMass} from '@/lib/aircraft';
import {autopilot,indicatedAlt,glidePath,planRemaining,newAutopilot,shortMode} from '@/lib/autopilot';
import {atmosphere,windAt} from '@/lib/weather';
import {loadMetars,loadModel,weatherAt,type Metar} from '@/lib/weatherClient';
import {clamp} from '@/lib/flight';

declare global{interface Window{Cesium:typeof Cesium;CESIUM_BASE_URL:string;}}
let cesiumLoading:Promise<typeof Cesium>|undefined;
function loadCesium(){return cesiumLoading??=new Promise((resolve,reject)=>{if(window.Cesium)return resolve(window.Cesium);window.CESIUM_BASE_URL='/cesium/';const s=document.createElement('script');s.src='/cesium/Cesium.js';s.onload=()=>resolve(window.Cesium);s.onerror=()=>reject(new Error('The globe engine could not load.'));document.head.appendChild(s);});}
export type View={camera:number;clean:boolean;panel:boolean};
export type CanvasEvent={type:'touchdown';data:import('@/lib/flightModel').Touchdown;atArrival:boolean}|{type:'crash';reason:string}|{type:'ap';text:string};
type Props={room:WorldRoom|null;sim:Sim|null;view:View;sound:boolean;paused:boolean;shared:boolean;onMove:(p:WorldPlane)=>void;onTelemetry:(t:Telemetry)=>void;onEvent:(e:CanvasEvent)=>void;onError:(s:string)=>void};
const kt=.514444,ft=.3048,rad=Math.PI/180;
const EYE:Record<string,[number,number,number]>={trainer:[.55,-.28,1.0],twin:[2.3,-.3,1.15],jet:[15.8,-.55,2.35]};
const CHASE:Record<string,number>={trainer:20,twin:28,jet:72};
function timeFor(preset:TimePreset,lat:number,lon:number){const now=new Date();if(preset==='live')return now;const day=new Date(Date.UTC(now.getUTCFullYear(),now.getUTCMonth(),now.getUTCDate()));const solar=(h:number)=>new Date(day.getTime()+((h-lon/15+48)%24)*3600000);
 if(preset==='dawn'||preset==='sunset'){let best=solar(preset==='dawn'?6:18),score=1e9;for(let h=preset==='dawn'?3:14;h<(preset==='dawn'?11:22);h+=1/12){const d=solar(h),e=sunElevation(d,lat,lon),want=preset==='dawn'?3:2.5,s=Math.abs(e-want);if(s<score){score=s;best=d;}}return best;}
 return solar({morning:9,noon:12.5,afternoon:15.5,night:23}[preset] as number);}
export default function WorldCanvas(props:Props){
 const mount=useRef<HTMLDivElement>(null),cockpitMount=useRef<HTMLDivElement>(null),panelRef=useRef<HTMLCanvasElement>(null),live=useRef(props);live.current=props;const [loading,setLoading]=useState(true),[status,setStatus]=useState('Loading globe, terrain and aircraft…');
 useEffect(()=>{
  let dead=false,viewer:Cesium.Viewer|undefined,frame=0,audio:AircraftAudio|undefined,renderer:THREE.WebGLRenderer|undefined,cockpitScene:THREE.Scene|undefined;const smooth={p:0,r:0,y:0,gp:0,gr:0},camSpring={h:NaN,p:0,range:30};const ramp=(v:number,target:number,dt:number)=>{if(target===0){const d=dt*4.5;return Math.abs(v)<=d?0:v-Math.sign(v)*d;}if(v!==0&&Math.sign(v)!==Math.sign(target))return v+Math.sign(target)*dt*8;const rate=Math.abs(v)<.4?2.2:1.1,next=v+Math.sign(target)*rate*dt;return Math.abs(next)>Math.abs(target)?target:next;};const keys=new Set<string>(),look={yaw:0,pitch:0,zoom:1,orbit:0};let drag=false,lastPointer=[0,0];const speaker=new Speaker();const cleanups:(()=>void)[]=[];
  const keydown=(e:KeyboardEvent)=>{if((e.target as HTMLElement)?.matches('input[type=text],input[type=search],input:not([type]),textarea,select'))return;if(['Space','ArrowUp','ArrowDown','ArrowLeft','ArrowRight','Slash','F2','Period','PageUp','PageDown'].includes(e.code))e.preventDefault();keys.add(e.code);if(e.code==='Home')look.yaw=look.pitch=0;
   const sim=live.current.sim;if(!sim||e.repeat||live.current.paused)return;const a=spec(sim.aircraft),i=sim.input,ap=sim.ap,det=a.flapDetents;
   const nearest=det.reduce((b,v,k)=>Math.abs(v-i.flaps)<Math.abs(det[b]-i.flaps)?k:b,0);
   switch(e.code){case 'KeyI':i.engine=!i.engine;break;case 'KeyE':if(e.ctrlKey){e.preventDefault();i.engine=true;i.parking=false;}break;case 'KeyG':if(a.gearRetract)i.gear=!i.gear;break;case 'KeyV':i.flaps=det[clamp(nearest+(e.shiftKey?-1:1),0,det.length-1)];break;
    case 'Slash':i.spoilers=i.spoilers>.75?0:i.spoilers+.5;break;case 'KeyF':case 'F2':if(a.engine==='jet')i.reverse=!i.reverse;break;case 'Period':if(e.ctrlKey)i.parking=!i.parking;break;
    case 'KeyP':ap.master=!ap.master;ap.copilot=false;if(ap.master){if(ap.lat==='TO'||ap.lat==='ROLLOUT')ap.lat='HDG';if(ap.vert==='TO'||ap.vert==='PIT'||ap.vert==='FLARE')ap.vert='VS';}live.current.onEvent({type:'ap',text:ap.master?'AUTOPILOT ON':'AUTOPILOT OFF'});audioTone(ap.master?'click':'ap');break;
    case 'KeyT':ap.athr=!ap.athr;break;case 'KeyB':if(e.shiftKey)ap.std=!ap.std;else{ap.baro=Math.round(sim.wx?.qnh??1013);ap.std=false;}break;
    case 'BracketLeft':case 'Numpad1':i.trim=clamp(i.trim-.04,-1,1);break;case 'BracketRight':case 'Numpad7':i.trim=clamp(i.trim+.04,-1,1);break;}};
  const keyup=(e:KeyboardEvent)=>keys.delete(e.code),blur=()=>{keys.clear();drag=false;};window.addEventListener('keydown',keydown);window.addEventListener('keyup',keyup);window.addEventListener('blur',blur);
  const el=mount.current;const pointerDown=(e:PointerEvent)=>{if(e.button!==0)return;drag=true;lastPointer=[e.clientX,e.clientY];el?.setPointerCapture(e.pointerId);},pointerMove=(e:PointerEvent)=>{if(!drag)return;const dx=e.clientX-lastPointer[0],dy=e.clientY-lastPointer[1];if(live.current.view.camera===1){look.yaw=clamp(look.yaw+dx*.16,-150,150);look.pitch=clamp(look.pitch-dy*.13,-40,50);}else{look.orbit+=dx*.3;look.pitch=clamp(look.pitch-dy*.15,-60,70);}lastPointer=[e.clientX,e.clientY];},pointerUp=()=>{drag=false;},wheel=(e:WheelEvent)=>{e.preventDefault();look.zoom=clamp(look.zoom*(e.deltaY>0?1.1:.9),.3,6);};
  el?.addEventListener('pointerdown',pointerDown);el?.addEventListener('pointermove',pointerMove);el?.addEventListener('pointerup',pointerUp);el?.addEventListener('pointercancel',pointerUp);el?.addEventListener('wheel',wheel,{passive:false});
  function audioTone(k:'ap'|'click'|'chime'|'master'){audio?.tone(k);}
  async function init(){try{
   setLoading(true);const C=await loadCesium();if(dead||!mount.current)return;const room=live.current.room,sim=live.current.sim,q=sim?.settings.quality??'balanced';
   if(room){flattenAirport(room.departure);flattenAirport(room.arrival);}
   viewer=new C.Viewer(mount.current,{terrainProvider:openTerrain(C),baseLayer:new C.ImageryLayer(worldImagery(C)),animation:false,timeline:false,geocoder:false,homeButton:false,sceneModePicker:false,baseLayerPicker:false,navigationHelpButton:false,fullscreenButton:false,selectionIndicator:false,infoBox:false,shouldAnimate:true,shadows:q==='high',contextOptions:{webgl:{alpha:false,antialias:true}},msaaSamples:q==='high'?4:q==='balanced'?2:1});
   const v=viewer,scene=v.scene,globe=scene.globe;v.resolutionScale=q==='performance'?.8:q==='high'?Math.min(2,devicePixelRatio):Math.min(1.25,devicePixelRatio);globe.maximumScreenSpaceError=q==='performance'?2.6:q==='high'?1.1:1.5;globe.tileCacheSize=q==='performance'?150:400;globe.loadingDescendantLimit=q==='performance'?10:20;globe.depthTestAgainstTerrain=true;globe.enableLighting=true;globe.dynamicAtmosphereLighting=true;globe.dynamicAtmosphereLightingFromSun=true;globe.showWaterEffect=true;globe.preloadSiblings=q!=='performance';
   scene.fog.enabled=true;scene.fog.density=1.6e-4;scene.fog.minimumBrightness=.08;scene.highDynamicRange=true;scene.postProcessStages.tonemapper=C.Tonemapper.PBR_NEUTRAL;scene.postProcessStages.exposure=1.05;scene.postProcessStages.fxaa.enabled=true;scene.screenSpaceCameraController.enableInputs=false;v.shadows=q!=='performance';if(scene.shadowMap){scene.shadowMap.maximumDistance=q==='high'?900:450;scene.shadowMap.softShadows=q==='high';scene.shadowMap.size=q==='high'?4096:2048;scene.shadowMap.darkness=.35;}globe.shadows=C.ShadowMode.RECEIVE_ONLY;
   if(q!=='performance'){const flare=C.PostProcessStageLibrary.createLensFlareStage();flare.uniforms.intensity=.55;flare.uniforms.distortion=8;flare.uniforms.ghostDispersal=.35;flare.uniforms.haloWidth=.35;flare.uniforms.dirtAmount=.25;flare.uniforms.earthRadius=C.Ellipsoid.WGS84.maximumRadius;scene.postProcessStages.add(flare);}
   const hi=v.imageryLayers.addImageryProvider(sentinelImagery(C));hi.contrast=1.08;hi.saturation=1.12;hi.gamma=1.04;hi.nightAlpha=.35;for(const p of regionalImagery(C))v.imageryLayers.addImageryProvider(p);const night=v.imageryLayers.addImageryProvider(nightImagery(C));night.dayAlpha=0;night.nightAlpha=.95;night.brightness=1.6;
   if(!room||!sim){v.camera.setView({destination:C.Cartesian3.fromDegrees(139.2,35.2,260000),orientation:{heading:C.Math.toRadians(20),pitch:-.62,roll:0}});const spin=()=>{if(dead||!viewer||viewer.isDestroyed())return;viewer.camera.rotate(C.Cartesian3.UNIT_Z,-.00004);frame=requestAnimationFrame(spin);};frame=requestAnimationFrame(spin);setLoading(false);return;}
   const a=spec(sim.aircraft),model=a.model,scaleOf=(k:string)=>k==='twin'?.5:1,urls:Record<string,string>={twin:'/flight/models/Cesium_Air.glb',trainer:await aircraftModelUrl('trainer'),jet:await aircraftModelUrl('jet')};if(dead)return;
   setStatus('Loading aircraft…');const craft=await C.Model.fromGltfAsync({url:urls[model],scale:scaleOf(model),minimumPixelSize:0,shadows:C.ShadowMode.ENABLED});if(dead){craft.destroy();return;}scene.primitives.add(craft);
   let remote:Cesium.Model|undefined,remoteKind='';const ownLights=new AircraftLights(C,scene,a.b,a.id==='jet'?37:a.id==='twin'?10:8.3),remoteLights=new AircraftLights(C,scene,11,9);
   const airfields=new AirfieldLayer(C,v);airfields.add(room.departure,true,room.runway);airfields.add(room.arrival,true,sim.plan.arrival.ident);
   const clouds=new CloudField(C,scene),wxStage=weatherStage(C,scene),traffic=new TrafficLayer(C,v,urls,{twin:.5,trainer:1,jet:1},{twin:1.15,trainer:1.22,jet:3.43});
   cleanups.push(()=>{airfields.destroy();clouds.destroy(scene);ownLights.destroy(scene);remoteLights.destroy(scene);traffic.destroy();});
   // Cockpit interior (three.js overlay) with glass displays painted on its panel.
   const cockpit=buildCockpit();cockpitScene=new THREE.Scene();cockpitScene.add(cockpit.group,new THREE.HemisphereLight('#d9e6ed','#475860',2.2));const keyLight=new THREE.DirectionalLight('#f2e2c2',2);keyLight.position.set(-2,3,2);cockpitScene.add(keyLight);const camera3=new THREE.PerspectiveCamera(68,1,.05,40);renderer=new THREE.WebGLRenderer({alpha:true,antialias:true});renderer.setPixelRatio(Math.min(1.4,devicePixelRatio));renderer.setClearColor(0,0);renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=.8;cockpitMount.current?.appendChild(renderer.domElement);
   let plane:WorldPlane={...room.planes[room.seat]},recovery=plane.recovery,last=performance.now(),send=0,telemetryAt=0,elapsed=0,ground=room.departure.elevation,water=false,groundReady=false,groundRequest=0,terrainNotice=false,lastTime='',lastRate=1,panelAt=0,cloudAt=0,wxAt=0,wxPos={lat:999,lon:999},trafficAt=0,nearAt={lat:999,lon:999},flash=0,lastRadio=99999,callouts=new Set<string>(),gpwsAt=0,spinning=false;
   const airports:Airport[]=[room.departure,room.arrival];let metars:Metar[]=[],modelWx:any=null,nearby:Airport[]=[];
   const refreshWeather=async()=>{wxPos={lat:plane.lat,lon:plane.lon};const [m,w]=await Promise.all([loadMetars([room.departure.id,room.arrival.id],plane),sim.settings.weather==='live'?loadModel(plane.lat,plane.lon):Promise.resolve(null)]);if(dead)return;metars=m;modelWx=w;if(sim.settings.weather!=='live'||metars.length||modelWx)sim.wx=weatherAt(sim.settings.weather,plane,metars,modelWx,ground);};
   sim.wx??=weatherAt(sim.settings.weather,plane,[],null,room.departure.elevation);void refreshWeather();
   const groundAtPoint=(lat:number,lon:number)=>{const h=globe.getHeight(C.Cartographic.fromDegrees(lon,lat));return h??ground;};
   setLoading(false);
   const render=(now:number)=>{if(dead||!viewer||!renderer||!cockpitScene)return;frame=requestAnimationFrame(render);const P=live.current,r=P.room,S=P.sim;if(!r||!S)return;const realDt=Math.min(.25,(now-last)/1000);last=now;
    const rate=P.shared?1:clamp(S.settings.simRate,1,16),dt=realDt*rate,i=S.input,ap=S.ap,wx=S.wx;
    if(r.planes[r.seat].recovery!==recovery){plane={...r.planes[r.seat]};recovery=plane.recovery;ground=r.departure.elevation;look.yaw=look.pitch=0;S.ap=newAutopilot(Math.round(plane.heading),S.plan.cruiseFt,ap.spd,ap.baro);S.plan.active=1;Object.assign(i,{throttle:0,flaps:plane.flaps,gear:true,engine:plane.engine,spoilers:0,reverse:false,parking:false});callouts.clear();}
    // Terrain below the aircraft: rendered height first, sampled open terrain as fallback, airports flattened.
    const h=globe.getHeight(C.Cartographic.fromDegrees(plane.lon,plane.lat));if(h!==undefined){ground=h;groundReady=true;}
    if(now-groundRequest>1000){groundRequest=now;void groundInfo(plane.lat,plane.lon).then(g=>{if(dead)return;water=g.water;if(h===undefined){ground=g.height;groundReady=true;}}).catch(()=>{if(!terrainNotice){P.onError('Some terrain tiles are unavailable. Scenery will retry; avoid low flight until terrain loads.');terrainNotice=true;}});}
    const pad=navigator.getGamepads?.().find(g=>g?.connected),axis=(k:number)=>pad&&Math.abs(pad.axes[k]??0)>.12?pad.axes[k]:0;
    const expo=(x:number)=>x*(.3+.7*x*x);smooth.p=ramp(smooth.p,clamp(((keys.has('KeyS')||keys.has('ArrowDown')?1:0)-(keys.has('KeyW')||keys.has('ArrowUp')?1:0))*(S.settings.invertPitch?-1:1)+S.touch.pitch,-1,1),realDt);smooth.r=ramp(smooth.r,clamp((keys.has('KeyD')||keys.has('ArrowRight')?1:0)-(keys.has('KeyA')||keys.has('ArrowLeft')?1:0)+S.touch.roll,-1,1),realDt);smooth.y=ramp(smooth.y,clamp((keys.has('KeyX')?1:0)-(keys.has('KeyZ')?1:0)+(pad?.buttons[5]?.pressed?1:0)-(pad?.buttons[4]?.pressed?1:0),-1,1),realDt);
    smooth.gp+=(expo(axis(1))-smooth.gp)*Math.min(1,realDt*14);smooth.gr+=(expo(axis(0))-smooth.gr)*Math.min(1,realDt*14);const stickP=clamp(smooth.p+smooth.gp,-1,1),stickR=clamp(smooth.r+smooth.gr,-1,1);
    if(!P.paused&&!document.hidden){elapsed+=dt;
     if(!ap.athr||!ap.master)i.throttle=clamp(i.throttle+realDt*((keys.has('KeyE')&&!keys.has('ControlLeft')||keys.has('PageUp')?.35:0)-(keys.has('KeyQ')||keys.has('PageDown')?.35:0)+(pad?.buttons[7]?.value??0)*.4-(pad?.buttons[6]?.value??0)*.4),0,1);
     if((ap.master||ap.copilot)&&(Math.abs(stickP)>.5||Math.abs(stickR)>.5)){ap.master=false;ap.copilot=false;audio?.tone('ap');P.onEvent({type:'ap',text:'AUTOPILOT DISCONNECTED'});}
     i.pitch=stickP;i.roll=stickR;i.rudder=smooth.y;i.brake=keys.has('Space')||keys.has('Period')&&!keys.has('ControlLeft')||!!pad?.buttons[1]?.pressed||S.touch.brake;i.stability=S.settings.stability;i.autoRudder=S.settings.autoRudder;i.unlimitedFuel=S.settings.unlimitedFuel;
     const list=[...airports,...nearby];let remaining=dt;while(remaining>1e-4){const chunk=Math.min(.05,remaining);remaining-=chunk;
      const out=autopilot(plane,S.ap,S.plan,i,wx,ground,chunk);if(out.throttle!==undefined)i.throttle=out.throttle;for(const k of ['flaps','gear','spoilers','reverse','autobrake'] as const)if(out[k]!==undefined)(i as any)[k]=out[k];
      if(out.callout&&S.settings.callouts)speaker.say(out.callout.toLowerCase(),'gpws');if(out.disconnect){audio?.tone('ap');P.onEvent({type:'ap',text:out.disconnect});}
      const ev=stepWorld(plane,chunk,{...i,brake:out.brake!==undefined?out.brake:i.brake,parking:i.parking,targets:out.targets},ground,nearRunway(plane,list),wx,water);
      if(ev.touchdown){const atArrival=geoDistance(plane,r.arrival)<6000;if(plane.airborne&&elapsed>20){S.touchdowns.push(ev.touchdown);P.onEvent({type:'touchdown',data:ev.touchdown,atArrival});}audio?.touchdown(ev.touchdown.fpm/196.85);}
      if(ev.crash){P.onEvent({type:'crash',reason:ev.crash});speaker.stop();break;}}
     look.yaw=clamp(look.yaw+axis(2)*realDt*60,-150,150);look.pitch=clamp(look.pitch-axis(3)*realDt*40,-40,50);}
    // Time of day and clock rate.
    const tkey=`${S.settings.time}`;if(lastTime!==tkey){lastTime=tkey;v.clock.currentTime=C.JulianDate.fromDate(timeFor(S.settings.time,r.departure.lat,r.departure.lon));}if(lastRate!==rate||v.clock.shouldAnimate===P.paused){lastRate=rate;v.clock.multiplier=rate;v.clock.shouldAnimate=!P.paused;}
    const date=C.JulianDate.toDate(v.clock.currentTime),sunEl=sunElevation(date,plane.lat,plane.lon),nightTime=sunEl<-4,dusk=clamp((sunEl+6)/12,0,1);
    // Weather refresh, clouds and screen-space weather.
    if((now-wxAt>600000||geoDistance(plane,wxPos)>60000)&&now-wxAt>20000){wxAt=now;void refreshWeather();}
    if(now-cloudAt>800){cloudAt=now;clouds.update(plane.lat,plane.lon,wx,.25+.75*dusk);}
    const inCloud=CloudField.inside(wx,plane.alt),topCloud=Math.max(0,...(wx?.clouds.map(c=>c.base)??[0])),precip=wx&&plane.alt<topCloud+300?wx.intensity:0,camCockpit=P.view.camera===1;
    if(wx?.precip==='thunder'&&Math.random()<realDt*.08)flash=.9;flash*=Math.exp(-realDt*7);
    Object.assign(wxStage.u,{u_vis:Math.max(60,wx?.visibility??40000),u_cloud:inCloud,u_rain:wx&&(wx.precip==='rain'||wx.precip==='thunder')?precip:0,u_snow:wx?.precip==='snow'?precip:0,u_flash:flash*(nightTime?.5:.25),u_time:now/1000,u_speed:camCockpit?Math.min(120,plane.speed):20});const fogL=.08+.72*dusk;wxStage.u.u_fog=new C.Cartesian3(fogL*.95,fogL*.97,fogL*1.02);
    // Nearby airports for landing anywhere, runway lights and live traffic.
    if(geoDistance(plane,nearAt)>20000){nearAt={lat:plane.lat,lon:plane.lon};void fetch(`/api/world?lat=${plane.lat.toFixed(2)}&lon=${plane.lon.toFixed(2)}&km=60`).then(x=>x.json()).then(d=>{if(dead)return;nearby=(d.airports??[]) as Airport[];nearby.forEach((ap2,k)=>{flattenAirport(ap2);airfields.add(ap2,k<4);});}).catch(()=>{});}
    airfields.update({lat:plane.lat,lon:plane.lon,alt:plane.alt},nightTime||sunEl<2,(wx?.visibility??99999)<5000,now/1000);
    if(S.settings.traffic&&now-trafficAt>8000){trafficAt=now;void fetch(`/api/traffic?lat=${plane.lat.toFixed(3)}&lon=${plane.lon.toFixed(3)}`).then(x=>x.json()).then(d=>{if(dead)return;const at=Date.now();void traffic.sync(((d.aircraft??[]) as LiveTraffic[]).map(t=>({...t,at})),groundAtPoint);}).catch(()=>{});}
    if(!S.settings.traffic&&traffic.list().length)void traffic.sync([],groundAtPoint);traffic.update(Date.now(),groundAtPoint);
    // Aircraft placement: wheels on the surface at the physics contact height.
    const lift=MODEL_GROUND[model]*scaleOf(model)-a.gearHeight,position=C.Cartesian3.fromDegrees(plane.lon,plane.lat,plane.alt+lift),hpr=new C.HeadingPitchRoll(C.Math.toRadians(plane.heading-90),plane.pitch,-plane.roll),fixed=C.Transforms.headingPitchRollToFixedFrame(position,hpr);
    craft.modelMatrix=fixed;craft.show=!camCockpit;if(model==='twin'&&craft.ready&&spinning!==((plane.n1??0)>.05)){spinning=(plane.n1??0)>.05;craft.activeAnimations.removeAll();if(spinning)craft.activeAnimations.addAll({loop:C.ModelAnimationLoop.REPEAT,multiplier:.5+(plane.n1??0)*2});}
    if(craft.ready&&model!=='twin'){try{const g=craft.getNode('gear');if(g)g.show=(plane.gearPos??1)>.5;const pr=craft.getNode('prop');if(pr)pr.matrix=C.Matrix4.multiply(pr.originalMatrix,C.Matrix4.fromRotationTranslation(C.Matrix3.fromRotationZ(now/1000*(plane.n1??0)*260%(Math.PI*2))),new C.Matrix4());}catch{}}
    const agl=plane.alt-(nearRunway(plane,[...airports,...nearby])?.airport.elevation??ground)-a.gearHeight;ownLights.update(fixed,now/1000,{engine:plane.engine,ground:plane.ground,agl,night:nightTime||sunEl<3});
    const other=r.planes[1-r.seat],otherKind=spec(other.aircraft).model,showRemote=!!r.names[1]&&Date.now()-other.seen<6000;
    if(showRemote&&remoteKind!==otherKind&&!remote?.isDestroyed?.()){remoteKind=otherKind;void C.Model.fromGltfAsync({url:urls[otherKind],scale:scaleOf(otherKind),color:C.Color.fromCssColorString('#8fceee'),colorBlendMode:C.ColorBlendMode.MIX,colorBlendAmount:.3}).then(m=>{if(dead||!viewer){m.destroy();return;}if(remote)scene.primitives.remove(remote);remote=m;scene.primitives.add(m);});}
    if(remote){remote.show=showRemote;const oa=spec(other.aircraft),rf=C.Transforms.headingPitchRollToFixedFrame(C.Cartesian3.fromDegrees(other.lon,other.lat,other.alt+MODEL_GROUND[otherKind]*scaleOf(otherKind)-oa.gearHeight),new C.HeadingPitchRoll(C.Math.toRadians(other.heading-90),other.pitch,-other.roll));remote.modelMatrix=rf;if(showRemote)remoteLights.update(rf,now/1000,{engine:other.engine,ground:other.ground,agl:500,night:nightTime});}
    // Cameras: chase, cockpit, orbit and tower.
    v.camera.lookAtTransform(C.Matrix4.IDENTITY);const cam=P.view.camera;
    if(cam===1){const [f,u,s2]=EYE[model],eye=C.Matrix4.multiplyByPoint(fixed,new C.Cartesian3(f,s2,u),new C.Cartesian3());v.camera.setView({destination:eye,orientation:{heading:C.Math.toRadians(plane.heading+look.yaw),pitch:plane.pitch+C.Math.toRadians(look.pitch-4),roll:-plane.roll}});(v.camera.frustum as Cesium.PerspectiveFrustum).fov=C.Math.toRadians(clamp(70/look.zoom,25,95));}
    else{(v.camera.frustum as Cesium.PerspectiveFrustum).fov=C.Math.toRadians(60);if(cam===3){const twr=[...airports].sort((x,y)=>geoDistance(plane,x)-geoDistance(plane,y))[0],tp=geoMove(twr.lat,twr.lon,45,350),tpos=C.Cartesian3.fromDegrees(tp.lon,tp.lat,twr.elevation+45),dir=C.Cartesian3.normalize(C.Cartesian3.subtract(position,tpos,new C.Cartesian3()),new C.Cartesian3());v.camera.setView({destination:tpos,orientation:{direction:dir,up:C.Ellipsoid.WGS84.geodeticSurfaceNormal(tpos,new C.Cartesian3())}});(v.camera.frustum as Cesium.PerspectiveFrustum).fov=C.Math.toRadians(clamp(Math.atan2(80,C.Cartesian3.distance(tpos,position))*2/rad,1.5,60));}
     else{if(cam===2&&!drag)look.orbit+=realDt*6;const k=Math.min(1,realDt*2.2);if(Number.isNaN(camSpring.h))camSpring.h=plane.heading;camSpring.h+=(((plane.heading-camSpring.h+540)%360)-180)*k;camSpring.p+=(Math.max(-.35,Math.min(.35,plane.pitch))*.35-camSpring.p)*k;camSpring.range+=(CHASE[model]*look.zoom*(cam===2?1.6:1)*(1+Math.min(.25,plane.speed/900))-camSpring.range)*Math.min(1,realDt*3);v.camera.lookAtTransform(C.Transforms.eastNorthUpToFixedFrame(position),new C.HeadingPitchRange(C.Math.toRadians(camSpring.h+look.orbit+(cam===2?70:0)),C.Math.toRadians(-7+look.pitch-(cam===2?14:0))-camSpring.p,camSpring.range));}}
    const camCarto=v.camera.positionCartographic,camGround=globe.getHeight(camCarto);if(cam!==1&&camGround!==undefined&&camCarto.height<camGround+2){v.camera.lookAtTransform(C.Matrix4.IDENTITY);v.camera.setView({destination:C.Cartesian3.fromRadians(camCarto.longitude,camCarto.latitude,camGround+2),orientation:{heading:v.camera.heading,pitch:v.camera.pitch,roll:0}});}
    // Cockpit overlay.
    const host=mount.current!,size=host.getBoundingClientRect();if(renderer.domElement.width!==Math.round(size.width*renderer.getPixelRatio())||renderer.domElement.height!==Math.round(size.height*renderer.getPixelRatio())){renderer.setSize(size.width,size.height);camera3.aspect=size.width/size.height;camera3.updateProjectionMatrix();cockpit.group.scale.x=Math.min(1,camera3.aspect/.9);}
    camera3.rotation.set(C.Math.toRadians(look.pitch),-C.Math.toRadians(look.yaw),0,'YXZ');camera3.fov=clamp(68/look.zoom,25,95);camera3.updateProjectionMatrix();cockpitMount.current!.style.display=camCockpit?'block':'none';keyLight.intensity=.4+1.6*dusk;
    // Avionics, warnings, callouts and telemetry.
    const mass=aircraftMass(a,plane.fuel),vs=vSpeeds(a,mass),alt=indicatedAlt(plane,wx,ap)/ft,radio=Math.max(0,agl/ft),ias=(plane.ias??0)/kt,wind=windAt(wx,plane.alt),atm=atmosphere(plane.alt,wx??undefined),vsFpm=plane.vertical*196.85;
    const flapIdx=a.flapDetents.reduce((b,x,k)=>Math.abs(x-plane.flaps)<Math.abs(a.flapDetents[b]-plane.flaps)?k:b,0),vfe=a.flapSpeeds[flapIdx]??a.vne,vmax=Math.min(a.vne,a.mmo<1?a.mmo/Math.max(.1,plane.mach??.1)*ias:999);
    const warnings:string[]=[],cautions:string[]=[];if(plane.crashed)warnings.push('CRASH');if(plane.stall)warnings.push('STALL');if(!plane.ground&&radio<1200&&vsFpm<-1200&&radio/(-vsFpm/60)<14)warnings.push('PULL UP');if(ias>vmax+3)warnings.push('OVERSPEED');if(!plane.ground&&flapIdx>0&&ias>vfe+5)warnings.push('FLAP OVERSPEED');
    const gearWarn=a.gearRetract&&!plane.ground&&(plane.gearPos??1)<.95&&radio<800&&vsFpm<-300;if(gearWarn)cautions.push('GEAR NOT DOWN');if(!plane.ground&&radio<2000&&vsFpm<-2200)cautions.push('SINK RATE');if(Math.abs(plane.roll)>(a.fbw?45:50)*rad)cautions.push('BANK ANGLE');if(plane.fuel<8)cautions.push('LOW FUEL');if(i.parking&&plane.ground)cautions.push('PARKING BRAKE');if(!plane.engine&&!plane.ground)cautions.push('ENGINE OUT');if(plane.tailStrike)cautions.push('TAIL STRIKE');
    if(S.settings.callouts&&!P.paused&&!plane.crashed){const say=(k:string,text:string,urgent=false)=>{if(!callouts.has(k)){callouts.add(k);speaker.say(text,'gpws',urgent);}};
     if(!plane.ground&&vsFpm<-200){for(const [h,word] of [[2500,'twenty five hundred'],[1000,'one thousand'],[500,'five hundred'],[100,'one hundred'],[50,'fifty'],[40,'forty'],[30,'thirty'],[20,'twenty'],[10,'ten']] as [number,string][])if(lastRadio>h&&radio<=h&&(a.engine==='jet'||h>=100))say(`ra${h}`,word,h<=50);if(lastRadio>200&&radio<=200&&ap.apr)say('mins','minimums');if(a.engine==='jet'&&radio<25&&i.throttle>.12&&lastRadio>=25)say('retard','retard',true);}
     if(radio>3000)['ra2500','ra1000','ra500','ra100','ra50','ra40','ra30','ra20','ra10','mins','retard'].forEach(k=>callouts.delete(k));
     if(plane.ground&&!plane.airborne&&a.engine==='jet'){if(ias>vs.v1)say('v1','vee one');if(ias>vs.vr)say('vr','rotate');}if(!plane.ground&&plane.vertical>2&&radio>30&&radio<400)say('posrate','positive rate');if(plane.ground&&ias<20){callouts.delete('v1');callouts.delete('vr');callouts.delete('posrate');}
     if(now-gpwsAt>2500){const g=warnings.includes('PULL UP')?'pull up':cautions.includes('SINK RATE')?'sink rate':gearWarn&&radio<500?'too low gear':cautions.includes('BANK ANGLE')&&a.engine==='jet'?'bank angle':plane.stall&&a.engine==='jet'?'stall':'';if(g){gpwsAt=now;speaker.say(g,'gpws',true);}}}
    lastRadio=radio;
    const loc=S.plan&&geoDistance(plane,S.plan.arrival)<40000?glidePath(plane,S.plan.arrival):null,remainingDist=planRemaining(plane,S.plan),wp=S.plan.waypoints[S.plan.active];
    if(now-panelAt>66&&(P.view.panel&&!P.view.clean||camCockpit)){panelAt=now;const route:NavPoint[]=[...S.plan.waypoints.map(w=>({id:w.id,lat:w.lat,lon:w.lon,kind:'wpt' as const})),...nearby.slice(0,12).map(x=>({id:x.id,lat:x.lat,lon:x.lon,kind:'apt' as const}))];
     const data:AvionicsData={ias,tas:plane.speed/kt,gs:(plane.gs??0)/kt,mach:plane.mach??0,alt,baro:ap.baro,std:ap.std,vs:vsFpm,pitch:plane.pitch,roll:plane.roll,heading:plane.heading,track:plane.track??plane.heading,beta:plane.beta??0,aoa:(plane.aoa??0),altSel:ap.alt,hdgSel:ap.hdg,spdSel:ap.spd,vsSel:ap.vs,ap:{master:ap.master,athr:ap.athr,athrMode:ap.athr?ap.athrMode||'SPEED':'',lat:ap.master||ap.fd?shortMode(ap).lat:'',vert:ap.master||ap.fd?shortMode(ap).vert:'',arm:shortMode(ap).arm,fd:ap.fd},fdPitch:null,fdBank:null,
      v:{vs:vs.vs,vs0:vs.vs0,vr:plane.ground?vs.vr:0,v2:a.engine==='jet'&&radio<3000?vs.v2:0,vref:radio<4000&&!plane.ground?vs.vref:0,vfe,vmax,green:a.engine==='jet'?vs.green:0},radio,loc:loc&&loc.along<0?loc.locDeg:null,gsDev:loc&&loc.along<0&&loc.along>-30000?loc.gsDeg:null,lat:plane.lat,lon:plane.lon,route,activeId:wp?.id??'',distNext:wp?geoDistance(plane,wp)/1852:0,distDest:remainingDist/1852,dest:r.arrival.id,eteMin:remainingDist/Math.max(20,plane.gs??0)/60,
      traffic:traffic.list().map(t=>({id:t.hex,label:t.flight,lat:t.lat,lon:t.lon,alt:t.alt,rate:t.rate,ground:t.ground})),wind:{dir:wind.dir,speed:wind.speed/kt},oat:atm.T-273.15,engine:a.engine,engines:a.engines,n1:plane.n1??0,running:plane.engine,ff:plane.ff??0,fuelKg:plane.fuel/100*a.fuelMax,fuelMax:a.fuelMax,flaps:a.flapLabels[flapIdx],flapPos:plane.flaps,gearPos:plane.gearPos??1,gearDown:plane.gear,retract:a.gearRetract,spoilers:plane.spoilers??0,brakes:plane.brakes??0,parking:i.parking,trim:i.trim,reverse:!!plane.reverse,
      warnings,cautions,range:radio<2500||plane.ground?5:radio<10000?20:40,utc:date.toISOString().slice(11,16),power:plane.engine||(plane.n1??0)>.02||!plane.ground,airportRunways:[r.departure,r.arrival,...nearby.slice(0,6)].flatMap(x=>x.runways.slice(0,4).map(rw=>({a:{lat:rw.lat,lon:rw.lon},b:{lat:rw.endLat,lon:rw.endLon}})))};
     if(ap.fd&&!plane.ground){const outFd=ap.i;data.fdBank=outFd?.bank??null;data.fdPitch=plane.law?.th??null;}
     const pc=panelRef.current;if(pc&&P.view.panel&&!P.view.clean&&!camCockpit){const w=pc.clientWidth,hh=pc.clientHeight,dpr=Math.min(2,devicePixelRatio);if(pc.width!==Math.round(w*dpr)){pc.width=Math.round(w*dpr);pc.height=Math.round(hh*dpr);}const c2=pc.getContext('2d')!;c2.setTransform(dpr,0,0,dpr,0,0);drawPanel(c2,w,hh,data);}
     if(camCockpit){drawPanel(cockpit.panel.ctx,1024,256,data);cockpit.panel.texture.needsUpdate=true;const nc=cockpit.panel.nav,f=S.atc.freqs(),st=S.atc.station();nc.fillStyle='#07120f';nc.fillRect(0,0,512,256);nc.fillStyle='#7df0c8';nc.font='bold 22px monospace';nc.textAlign='left';nc.fillText(`COM1 ${st.f.padEnd(7,'0')}`,20,50);nc.font='16px monospace';nc.fillText(st.name.slice(0,30),20,80);nc.fillText(`XPDR ${S.atc.squawk}  ALT`,20,120);nc.fillText(`NAV1 ILS ${S.plan.arrival.ident}  ${r.arrival.id}`,20,155);nc.fillText(`QNH ${ap.std?'STD':Math.round(ap.baro)}   ${data.utc}Z`,20,190);nc.fillText(`FUEL ${Math.round(data.fuelKg)} KG`,20,225);cockpit.panel.navTexture.needsUpdate=true;cockpit.controls(i.roll,-i.pitch*.5,i.throttle);}}
    if(camCockpit)renderer.render(cockpitScene,camera3);
    // Sound.
    if(P.sound&&!P.paused&&!document.hidden){audio??=new AircraftAudio(a.engine,a.engines);audio.update({n1:plane.n1??0,running:plane.engine,speed:plane.speed,ground:plane.ground,cockpit:camCockpit,stall:!!plane.stall||(a.engine!=='jet'&&!plane.ground&&ias<worldStallSpeed(plane)/kt+5&&ias>20),gearWarn,overspeed:warnings.includes('OVERSPEED'),reverse:!!plane.reverse,spoilers:plane.spoilers??0,rain:camCockpit?(wxStage.u.u_rain+wxStage.u.u_snow*.3):0});}else if(audio){audio.dispose();audio=undefined;}
    speaker.enabled=P.sound&&S.settings.voice;
    // ATC.
    if(now-telemetryAt>200){const snap={lat:plane.lat,lon:plane.lon,alt,agl:radio,ias,vs:vsFpm,heading:plane.heading,ground:plane.ground,airborne:plane.airborne,engine:plane.engine,crashed:!!plane.crashed,distDest:geoDistance(plane,r.arrival),locCaptured:!!ap.i?.locCap,onRunway:!!nearRunway(plane,airports),traffic:traffic.list().map(t=>({id:t.hex,type:t.type,flight:t.flight,lat:t.lat,lon:t.lon,alt:t.alt,track:t.track,ground:t.ground})),now:Date.now()};S.snap=snap;
     if(!P.paused){const lines=S.atc.tick(snap);for(const ln of lines){S.atcLines.push(ln);if(S.atcLines.length>80)S.atcLines.shift();if(ln.who==='atc'||ln.who==='atis')audio?.tone('click');speaker.say(ln.speech,ln.who==='pilot'?'pilot':'atc');}}
     P.onTelemetry({plane:{...plane},agl:radio*ft,altInd:alt,remaining:geoDistance(plane,r.arrival),bearing:geoBearing(plane,r.arrival),elapsed,terrainReady:groundReady,wx,wind:{dir:wind.dir,speed:wind.speed/kt},oat:atm.T-273.15,nextWp:wp?.id??'',distNext:wp?geoDistance(plane,wp):0,warnings,cautions,traffic:traffic.list().length,input:{...i},ap:{...ap,i:{...ap.i}},rate,night:nightTime});telemetryAt=now;}
    if(now-send>500&&!P.paused){P.onMove({...plane,law:undefined});send=now;}
   };frame=requestAnimationFrame(render);
  }catch(e){if(!dead){setLoading(false);live.current.onError(e instanceof Error?e.message:'Globe could not start.');}}}
  void init();return()=>{dead=true;cancelAnimationFrame(frame);window.removeEventListener('keydown',keydown);window.removeEventListener('keyup',keyup);window.removeEventListener('blur',blur);el?.removeEventListener('pointerdown',pointerDown);el?.removeEventListener('pointermove',pointerMove);el?.removeEventListener('pointerup',pointerUp);el?.removeEventListener('pointercancel',pointerUp);el?.removeEventListener('wheel',wheel);speaker.stop();audio?.dispose();for(const c of cleanups){try{c();}catch{}}if(viewer&&!viewer.isDestroyed())viewer.destroy();if(cockpitScene)disposeWorld(cockpitScene);renderer?.dispose();renderer?.domElement.remove();};
 },[props.room?.code,props.sim]);
 return <><div className="world-globe" ref={mount}/><div className="world-cockpit" ref={cockpitMount}/><canvas ref={panelRef} className={`glass-panel ${props.room&&props.view.panel&&!props.view.clean&&props.view.camera!==1?'':'hidden'}`}/>{loading&&<div className="world-loading"><span className="load-ring"/><h2>Preparing your world</h2><p>{status}</p></div>}</>;
}
