// Air traffic control: an IFR flow from clearance delivery to ground, using standard radio phraseology.
// Controllers react to what the aircraft actually does (altitude, position, runway, live traffic).
import {atis,windText,phonetic,atisLetter,type Weather} from './weather';
import {geoDistance,geoBearing,angleDiff} from './geo';
export type AtcLine={id:number;who:'atc'|'pilot'|'atis'|'info';station:string;freq:string;text:string;speech:string;time:number};
export type AtcOption={id:string;label:string};
export type AtcAirport={id:string;name:string;city:string;country:string;lat:number;lon:number;elevation:number;runway:string;runwayHeading:number;wx:Weather|null};
export type AtcSnap={lat:number;lon:number;alt:number;agl:number;ias:number;vs:number;heading:number;ground:boolean;airborne:boolean;engine:boolean;crashed:boolean;distDest:number;locCaptured:boolean;onRunway:boolean;traffic:{id:string;type:string;flight:string;lat:number;lon:number;alt:number|null;track:number;ground:boolean}[];now:number};
const WORDS='zero one two three four five six seven eight niner'.split(' ');
export const digits=(s:string)=>s.split('').map(ch=>/\d/.test(ch)?WORDS[Number(ch)]:/[A-Z]/i.test(ch)?phonetic(ch):ch==='.'?'decimal':'').filter(Boolean).join(' ');
const hundreds=(n:number)=>{const th=Math.floor(n/1000),h=Math.round(n%1000/100);return `${th?`${th>=10?digits(String(th)):WORDS[th].replace('niner','nine')} thousand`:''}${h?` ${WORDS[h].replace('niner','nine')} hundred`:''}`.trim();};
export function transitionAlt(country:string){return country==='US'||country==='CA'?18000:country==='JP'?14000:country==='GB'?6000:country==='IN'?4000:7000;}
export function altSpeech(ft:number,country:string){return ft>=transitionAlt(country)?`flight level ${digits(String(Math.round(ft/100)).padStart(3,'0'))}`:hundreds(Math.round(ft/100)*100);}
export function altText(ft:number,country:string){return ft>=transitionAlt(country)?`FL${String(Math.round(ft/100)).padStart(3,'0')}`:`${Math.round(ft/100)*100} ft`;}
const rwySpeech=(r:string)=>`runway ${digits(r.replace(/[LRC]$/,''))}${/L$/.test(r)?' left':/R$/.test(r)?' right':/C$/.test(r)?' center':''}`;
const hdgSpeech=(h:number)=>`heading ${digits(String(Math.round(h)%360||360).padStart(3,'0'))}`;
const AIRLINES:Record<string,string>={JAL:'Japan Air',ANA:'All Nippon',UAL:'United',DAL:'Delta',AAL:'American',BAW:'Speedbird',AFR:'Air France',DLH:'Lufthansa',SIA:'Singapore',QFA:'Qantas',AIC:'Air India',UAE:'Emirates',KLM:'KLM',CPA:'Cathay',SWA:'Southwest',RYR:'Ryanair',EZY:'Easy',THY:'Turkish',IGO:'Ifly'};
export function callsignSpeech(cs:string){const m=/^([A-Z]{3})(\d+[A-Z]?)$/i.exec(cs.replace(/\s/g,''));if(m&&AIRLINES[m[1].toUpperCase()])return `${AIRLINES[m[1].toUpperCase()]} ${digits(m[2])}`;if(/\d/.test(cs)&&/^[A-Z0-9-]+$/i.test(cs))return digits(cs.replace(/-/g,''));return cs;}
function hash(s:string){let h=2166136261;for(const c of s)h=Math.imul(h^c.charCodeAt(0),16777619);return h>>>0;}
const freq=(seed:string,lo:number,hi:number)=>{const steps=Math.round((hi-lo)/.025),v=lo+(hash(seed)%steps)*.025;return v.toFixed(3).replace(/0$/,'');};
const freqSpeech=(f:string)=>digits(f.replace(/0+$/,'').replace(/\.$/,''));
const countryName=(cc:string)=>{try{return new Intl.DisplayNames(['en'],{type:'region'}).of(cc)??cc;}catch{return cc;}};
export class AtcController{
 phase='preflight';assigned:number|null=null;squawk:string;log:AtcLine[]=[];private queue:{at:number;line:Omit<AtcLine,'id'|'time'>}[]=[];private n=0;private lastHandoff:{lat:number;lon:number};private devSince=0;private lastWarn=0;private reported=new Map<string,number>();private lowOnFinal=false;private ifr=false;center='';
 constructor(public callsign:string,public dep:AtcAirport,public arr:AtcAirport,public cruise:number,public jet:boolean){this.squawk=String(1000+hash(callsign+dep.id+arr.id)%6000).split('').map(d=>String(Math.min(7,Number(d)))).join('');if(['7500','7600','7700','1200'].includes(this.squawk))this.squawk='4521';this.lastHandoff={lat:dep.lat,lon:dep.lon};}
 private cs(){return callsignSpeech(this.callsign);}
 startAt(phase:'enroute'|'final'){this.ifr=true;this.phase=phase;this.cleared=phase==='final';this.assigned=phase==='enroute'?this.cruise:null;this.center=`${countryName(this.dep.country)} Control`;}
 freqs(){const d=this.dep.id,a=this.arr.id;return{delivery:freq(d+'del',121.65,121.95),ground:freq(d+'gnd',121.6,121.95),tower:freq(d+'twr',118,120.95),departure:freq(d+'dep',124,127.95),atis:freq(d+'atis',126,128.6),center:freq(this.center||'ctr',128,135.95),approach:freq(a+'app',119,125.95),arrTower:freq(a+'twr',118,120.95),arrGround:freq(a+'gnd',121.6,121.95),arrAtis:freq(a+'atis',126,128.6)};}
 private say(who:AtcLine['who'],station:string,f:string,text:string,speech:string,delay=0,now=Date.now()){const line={who,station,freq:f,text,speech};if(delay<=0){this.log.push({...line,id:++this.n,time:now});if(this.log.length>60)this.log.shift();}else this.queue.push({at:now+delay*1000,line});}
 private atc(station:string,f:string,text:string,speech:string,delay=2.2,now=Date.now()){this.say('atc',station,f,text,speech,delay,now);}
 private pilot(f:string,text:string,speech:string,now=Date.now()){this.say('pilot',this.callsign,f,text,speech,0,now);}
 private wxLine(a:AtcAirport){return a.wx?windText(a.wx):'wind calm';}
 private initialAlt(){return Math.min(this.cruise,this.jet?(transitionAlt(this.dep.country)>10000?10000:6000):Math.max(3000,Math.min(this.cruise,5000)));}
 options(s:AtcSnap):AtcOption[]{const o:AtcOption[]=[];const p=this.phase;
  if(p==='preflight'||p==='cleared'){if(this.dep.wx)o.push({id:'atis',label:`Listen to ${this.dep.id} ATIS`});if(!this.ifr)o.push({id:'clearance',label:`Request IFR clearance to ${this.arr.id}`});if(s.ground&&!s.airborne)o.push({id:'ready',label:`Ready for departure, runway ${this.dep.runway}`});}
  if(p==='takeoff'&&s.ground)o.push({id:'abort',label:'Rejecting takeoff'});
  if(['departure','enroute','descent'].includes(p)){o.push({id:'higher',label:'Request higher altitude'},{id:'lower',label:'Request lower altitude'},{id:'direct',label:`Request direct ${this.arr.id}`});}
  if(['enroute','descent'].includes(p))o.push({id:'descend',label:'Request descent for approach'});
  if(['descent','approach'].includes(p)&&this.arr.wx)o.push({id:'arratis',label:`Listen to ${this.arr.id} ATIS`});
  if(p==='approach'||p==='final')o.push({id:'goaround',label:'Going around'});
  if(!s.ground&&p!=='emergency')o.push({id:'mayday',label:'Declare emergency'});
  if(this.reported.size)o.push({id:'insight',label:'Traffic in sight'});
  return o;}
 request(id:string,s:AtcSnap){const f=this.freqs(),cs=this.callsign,css=this.cs(),now=s.now,dep=this.dep,arr=this.arr,city=(a:AtcAirport)=>a.city||a.name;
  if(id==='atis'||id==='arratis'){const a=id==='atis'?dep:arr;if(a.wx){const t=atis(a.name,a.wx,a.runway,'ILS');this.say('atis',`${a.id} ATIS`,id==='atis'?f.atis:f.arrAtis,t,t.replace(/(\d)/g,' $1 ').replace(/ 9 /g,' niner '),0,now);}return;}
  if(id==='clearance'){this.ifr=true;const init=this.initialAlt();this.pilot(f.delivery,`${city(dep)} Delivery, ${cs}, IFR to ${arr.id}, request clearance.`,`${city(dep)} delivery, ${css}, I F R to ${arr.name}, request clearance`,now);
   this.atc(`${city(dep)} Delivery`,f.delivery,`${cs}, cleared to ${arr.id} via direct. After departure fly runway heading, climb and maintain ${altText(init,dep.country)}, expect ${altText(this.cruise,dep.country)} ten minutes after departure. Departure frequency ${f.departure}, squawk ${this.squawk}.`,`${css}, cleared to ${arr.name} via direct. After departure fly runway heading, climb and maintain ${altSpeech(init,dep.country)}, expect ${altSpeech(this.cruise,dep.country)} one zero minutes after departure. Departure frequency ${freqSpeech(f.departure)}, squawk ${digits(this.squawk)}.`,2.5,now);
   this.queue.push({at:now+11000,line:{who:'pilot',station:cs,freq:f.delivery,text:`Cleared to ${arr.id}, runway heading, ${altText(init,dep.country)}, expect ${altText(this.cruise,dep.country)}, ${f.departure}, squawk ${this.squawk}, ${cs}.`,speech:`Cleared to ${arr.name}, runway heading, ${altSpeech(init,dep.country)}, expecting ${altSpeech(this.cruise,dep.country)}, ${freqSpeech(f.departure)}, squawk ${digits(this.squawk)}, ${css}`}});
   this.queue.push({at:now+16000,line:{who:'atc',station:`${city(dep)} Delivery`,freq:f.delivery,text:`${cs}, readback correct. Contact tower ${f.tower} when ready for departure.`,speech:`${css}, readback correct. Contact tower ${freqSpeech(f.tower)} when ready for departure.`}});this.assigned=init;this.phase='cleared';return;}
  if(id==='ready'){this.pilot(f.tower,`${city(dep)} Tower, ${cs}, holding short runway ${dep.runway}, ready for departure.`,`${city(dep)} tower, ${css}, ${rwySpeech(dep.runway)}, ready for departure`,now);
   if(!s.engine){this.atc(`${city(dep)} Tower`,f.tower,`${cs}, hold position, advise when engines are running.`,`${css}, hold position, advise when engines are running.`,2,now);return;}
   const traffic=s.traffic.find(t=>!t.ground&&t.alt!==null&&t.alt-dep.elevation<900&&geoDistance(t,dep)<9000&&Math.abs(angleDiff(geoBearing(dep,t),dep.runwayHeading+180))<20);
   if(traffic){this.atc(`${city(dep)} Tower`,f.tower,`${cs}, line up and wait runway ${dep.runway}, traffic on short final.`,`${css}, line up and wait ${rwySpeech(dep.runway)}, traffic on short final.`,2,now);this.queue.push({at:now+25000,line:{who:'atc',station:`${city(dep)} Tower`,freq:f.tower,text:`${cs}, ${this.wxLine(dep)}, runway ${dep.runway}, cleared for takeoff.`,speech:`${css}, ${this.wxLine(dep)}, ${rwySpeech(dep.runway)}, cleared for takeoff.`}});}
   else this.atc(`${city(dep)} Tower`,f.tower,`${cs}, ${this.wxLine(dep)}, runway ${dep.runway}, cleared for takeoff.`,`${css}, ${this.wxLine(dep)}, ${rwySpeech(dep.runway)}, cleared for takeoff.`,2.4,now);
   this.queue.push({at:now+(traffic?31000:7000),line:{who:'pilot',station:cs,freq:f.tower,text:`Cleared for takeoff runway ${dep.runway}, ${cs}.`,speech:`Cleared for takeoff ${rwySpeech(dep.runway)}, ${css}`}});this.phase='takeoff';if(!this.ifr)this.assigned=null;return;}
  if(id==='abort'){this.pilot(f.tower,`${cs}, stopping on the runway.`,`${css}, stopping`,now);this.atc(`${city(dep)} Tower`,f.tower,`${cs}, roger, advise when able to vacate.`,`${css}, roger, advise when able to vacate.`,2,now);this.phase='cleared';return;}
  if(id==='higher'||id==='lower'){const up=id==='higher',cur=Math.round(s.alt/1000)*1000,want=Math.max(2000,Math.min(this.jet?41000:this.cruise+4000,cur+(up?2000:-2000))),st=this.station();this.pilot(st.f,`${st.name}, ${cs}, request ${altText(want,dep.country)}.`,`${st.name}, ${css}, request ${altSpeech(want,dep.country)}`,now);
   this.atc(st.name,st.f,`${cs}, ${up?'climb':'descend'} and maintain ${altText(want,dep.country)}.`,`${css}, ${up?'climb':'descend'} and maintain ${altSpeech(want,dep.country)}.`,2.5,now);this.assigned=want;this.devSince=0;return;}
  if(id==='direct'){const st=this.station();this.pilot(st.f,`${cs}, request direct ${arr.id}.`,`${css}, request direct ${arr.name}`,now);this.atc(st.name,st.f,`${cs}, proceed direct ${arr.id}.`,`${css}, proceed direct ${arr.name}.`,2.5,now);return;}
  if(id==='descend'){this.topOfDescent(s,true);return;}
  if(id==='goaround'){this.goAround(s);return;}
  if(id==='mayday'){const st=this.station();this.phase='emergency';this.pilot(st.f,`Mayday mayday mayday, ${st.name}, ${cs}, declaring an emergency.`,`Mayday, mayday, mayday, ${st.name}, ${css}, declaring an emergency`,now);this.atc(st.name,st.f,`${cs}, roger mayday. All runways available, ${this.wxLine(arr)}. Say intentions and souls on board.`,`${css}, roger mayday. All runways available, ${this.wxLine(arr)}. Say intentions and souls on board.`,2.5,now);return;}
  if(id==='insight'){const st=this.station();this.reported.clear();this.pilot(st.f,`${cs}, traffic in sight.`,`${css}, traffic in sight`,now);this.atc(st.name,st.f,`${cs}, roger, maintain visual separation.`,`${css}, roger, maintain visual separation.`,2,now);}}
 station(){const f=this.freqs(),dep=this.dep,arr=this.arr;switch(this.phase){case 'preflight':case 'cleared':return{name:`${dep.city||dep.name} Delivery`,f:f.delivery};case 'takeoff':return{name:`${dep.city||dep.name} Tower`,f:f.tower};case 'departure':return{name:`${dep.city||dep.name} Departure`,f:f.departure};case 'approach':return{name:`${arr.city||arr.name} Approach`,f:f.approach};case 'final':return{name:`${arr.city||arr.name} Tower`,f:f.arrTower};case 'landed':case 'parked':return{name:`${arr.city||arr.name} Ground`,f:f.arrGround};default:return{name:this.center||`${countryName(dep.country)} Control`,f:f.center};}}
 private topOfDescent(s:AtcSnap,asked=false){const st=this.station(),cs=this.callsign,css=this.cs(),arr=this.arr,target=Math.round((arr.elevation*3.28084+(this.jet?3500:2000))/100)*100,init=this.jet?Math.max(target,Math.min(10000,Math.round(s.alt/1000)*1000)):target;
  if(asked)this.pilot(st.f,`${st.name}, ${cs}, request descent.`,`${st.name}, ${css}, request descent`,s.now);
  this.atc(st.name,st.f,`${cs}, descend and maintain ${altText(init,arr.country)}, expect ILS runway ${arr.runway} at ${arr.id}${arr.wx?`, information ${atisLetter(arr.wx.time)} is current, QNH ${Math.round(arr.wx.qnh)}`:''}.`,`${css}, descend and maintain ${altSpeech(init,arr.country)}, expect I L S ${rwySpeech(arr.runway)}${arr.wx?`, information ${atisLetter(arr.wx.time)} is current, Q N H ${digits(String(Math.round(arr.wx.qnh)))}`:''}.`,asked?2.5:0,s.now);
  this.queue.push({at:s.now+(asked?9000:6000),line:{who:'pilot',station:cs,freq:st.f,text:`Descend ${altText(init,arr.country)}, expect ILS ${arr.runway}, ${cs}.`,speech:`Descend ${altSpeech(init,arr.country)}, expect I L S ${rwySpeech(arr.runway)}, ${css}`}});this.assigned=init;this.devSince=0;this.phase='descent';}
 private goAround(s:AtcSnap){const f=this.freqs(),cs=this.callsign,css=this.cs(),arr=this.arr,alt=Math.round((arr.elevation*3.28084+(this.jet?3000:2000))/100)*100;this.pilot(f.arrTower,`${cs}, going around.`,`${css}, going around`,s.now);this.atc(`${arr.city||arr.name} Tower`,f.arrTower,`${cs}, roger, fly runway heading, climb and maintain ${altText(alt,arr.country)}, contact approach ${f.approach}.`,`${css}, roger, fly runway heading, climb and maintain ${altSpeech(alt,arr.country)}, contact approach ${freqSpeech(f.approach)}.`,2,s.now);this.assigned=alt;this.phase='approach';this.lowOnFinal=false;this.devSince=0;this.cleared=false;}
 private cleared=false;
 /** Advance controllers; returns lines that became audible. */
 tick(s:AtcSnap){const now=s.now,f=this.freqs(),cs=this.callsign,css=this.cs(),dep=this.dep,arr=this.arr,before=this.log.length;
  for(const q of this.queue.filter(q=>q.at<=now)){this.log.push({...q.line,id:++this.n,time:now});}this.queue=this.queue.filter(q=>q.at>now);
  if(s.crashed&&this.phase!=='crashed'){const st=this.station();this.phase='crashed';this.atc(st.name,st.f,`${cs}, ${st.name}, emergency services are on their way. All stations, ${st.name}, stop transmitting, emergency in progress.`,`${css}, emergency services are on their way. All stations, stop transmitting, emergency in progress.`,1.5,now);}
  if(this.phase==='crashed')return this.log.slice(before);
  if((this.phase==='preflight'||this.phase==='cleared')&&s.airborne&&!s.ground){this.phase='takeoff';}
  if(this.phase==='takeoff'&&!s.ground&&s.agl>(this.jet?800:500)){this.phase='departure';const st=`${dep.city||dep.name} Departure`;this.atc(`${dep.city||dep.name} Tower`,f.tower,`${cs}, contact departure ${f.departure}. Good day.`,`${css}, contact departure ${freqSpeech(f.departure)}. Good day.`,.5,now);
   this.queue.push({at:now+6000,line:{who:'pilot',station:cs,freq:f.departure,text:`${st}, ${cs}, passing ${altText(Math.round(s.alt/100)*100,dep.country)} climbing ${altText(this.assigned??this.initialAlt(),dep.country)}.`,speech:`${st}, ${css}, passing ${altSpeech(Math.round(s.alt/100)*100,dep.country)}, climbing ${altSpeech(this.assigned??this.initialAlt(),dep.country)}`}});
   this.queue.push({at:now+10000,line:{who:'atc',station:st,freq:f.departure,text:`${cs}, ${st}, radar contact. Climb and maintain ${altText(this.cruise,dep.country)}, proceed direct ${arr.id}.`,speech:`${css}, radar contact. Climb and maintain ${altSpeech(this.cruise,dep.country)}, proceed direct ${arr.name}.`}});this.assigned=this.cruise;}
  if(this.phase==='departure'&&geoDistance(s,dep)>(this.jet?60000:30000)){this.handoff(s);}
  if(this.phase==='enroute'&&geoDistance(s,this.lastHandoff)>300000)this.handoff(s);
  const descentStart=Math.max(0,(s.alt-arr.elevation*3.28084-3000))/(this.jet?300:500)*1852+(this.jet?25000:8000);
  if((this.phase==='enroute'||this.phase==='departure')&&s.distDest<descentStart&&s.distDest>12000&&!s.ground)this.topOfDescent(s);
  if(this.phase==='descent'&&s.distDest<(this.jet?55000:30000)&&s.alt<(this.jet?14000:9000)){this.phase='approach';const st=`${arr.city||arr.name} Approach`,c=this.station();this.atc(c.name,c.f,`${cs}, contact ${st} ${f.approach}.`,`${css}, contact ${st} ${freqSpeech(f.approach)}.`,.5,now);
   this.queue.push({at:now+6000,line:{who:'pilot',station:cs,freq:f.approach,text:`${st}, ${cs}, ${altText(Math.round(s.alt/100)*100,arr.country)}${arr.wx?`, information ${atisLetter(arr.wx.time)}`:''}.`,speech:`${st}, ${css}, ${altSpeech(Math.round(s.alt/100)*100,arr.country)}${arr.wx?`, information ${atisLetter(arr.wx.time)}`:''}`}});
   this.queue.push({at:now+10000,line:{who:'atc',station:st,freq:f.approach,text:`${cs}, ${st}, expect vectors ILS runway ${arr.runway}${arr.wx?`, QNH ${Math.round(arr.wx.qnh)}`:''}.`,speech:`${css}, expect vectors I L S ${rwySpeech(arr.runway)}${arr.wx?`, Q N H ${digits(String(Math.round(arr.wx.qnh)))}`:''}.`}});}
  if(this.phase==='approach'&&!this.cleared&&s.distDest<(this.jet?32000:20000)){this.cleared=true;const st=`${arr.city||arr.name} Approach`,brg=geoBearing(s,arr),intercept=(arr.runwayHeading+Math.sign(angleDiff(brg,arr.runwayHeading)||1)*30+360)%360,alt=Math.round((arr.elevation*3.28084+(this.jet?3000:2000))/100)*100;
   this.atc(st,f.approach,`${cs}, turn heading ${String(Math.round(intercept)).padStart(3,'0')}, maintain ${altText(alt,arr.country)} until established on the localizer, cleared ILS runway ${arr.runway} approach.`,`${css}, turn ${hdgSpeech(intercept)}, maintain ${altSpeech(alt,arr.country)} until established on the localizer, cleared I L S ${rwySpeech(arr.runway)} approach.`,.5,now);this.assigned=alt;this.devSince=0;
   this.queue.push({at:now+9000,line:{who:'pilot',station:cs,freq:f.approach,text:`Heading ${String(Math.round(intercept)).padStart(3,'0')}, ${altText(alt,arr.country)} until established, cleared ILS ${arr.runway}, ${cs}.`,speech:`${hdgSpeech(intercept)}, ${altSpeech(alt,arr.country)} until established, cleared I L S ${rwySpeech(arr.runway)}, ${css}`}});}
  if(this.phase==='approach'&&this.cleared&&(s.locCaptured||s.distDest<12000)&&s.distDest<22000){this.phase='final';this.assigned=null;const twr=`${arr.city||arr.name} Tower`;this.atc(`${arr.city||arr.name} Approach`,f.approach,`${cs}, contact tower ${f.arrTower}.`,`${css}, contact tower ${freqSpeech(f.arrTower)}.`,.5,now);
   this.queue.push({at:now+5000,line:{who:'pilot',station:cs,freq:f.arrTower,text:`${twr}, ${cs}, established ILS runway ${arr.runway}.`,speech:`${twr}, ${css}, established I L S ${rwySpeech(arr.runway)}`}});
   this.queue.push({at:now+9000,line:{who:'atc',station:twr,freq:f.arrTower,text:`${cs}, ${twr}, ${this.wxLine(arr)}, runway ${arr.runway}, cleared to land.`,speech:`${css}, ${this.wxLine(arr)}, ${rwySpeech(arr.runway)}, cleared to land.`}});
   this.queue.push({at:now+14000,line:{who:'pilot',station:cs,freq:f.arrTower,text:`Cleared to land runway ${arr.runway}, ${cs}.`,speech:`Cleared to land ${rwySpeech(arr.runway)}, ${css}`}});}
  if(this.phase==='final'){if(s.agl<700&&!s.ground)this.lowOnFinal=true;if(this.lowOnFinal&&s.vs>700&&s.agl>200&&!s.ground&&s.distDest<6000)this.goAround(s);}
  if((this.phase==='final'||this.phase==='approach'||this.phase==='emergency')&&s.ground&&s.airborne&&s.ias<70&&geoDistance(s,arr)<6000){this.phase='landed';const twr=`${arr.city||arr.name} Tower`;this.atc(twr,f.arrTower,`${cs}, welcome to ${arr.city||arr.name}. Vacate the runway when able, contact ground ${f.arrGround}.`,`${css}, welcome to ${arr.city||arr.name}. Vacate the runway when able, contact ground ${freqSpeech(f.arrGround)}.`,1.5,now);
   this.queue.push({at:now+11000,line:{who:'atc',station:`${arr.city||arr.name} Ground`,freq:f.arrGround,text:`${cs}, taxi to the gate. Thank you for flying today.`,speech:`${css}, taxi to the gate. Thank you for flying today.`}});}
  // Altitude deviation monitoring once established at the wrong level.
  if(this.assigned&&!s.ground&&['departure','enroute','descent','approach'].includes(this.phase)){const off=Math.abs(s.alt-this.assigned)>350&&Math.abs(s.vs)<300;if(off){if(!this.devSince)this.devSince=now;if(now-this.devSince>30000&&now-this.lastWarn>90000){const st=this.station();this.lastWarn=now;this.atc(st.name,st.f,`${cs}, check altitude, maintain ${altText(this.assigned,arr.country)}.`,`${css}, check altitude, maintain ${altSpeech(this.assigned,arr.country)}.`,.5,now);}}else this.devSince=0;}
  // Traffic advisories from live ADS-B traffic.
  if(!s.ground&&now-this.lastWarn>40000){for(const t of s.traffic){if(t.ground||t.alt===null)continue;const d=geoDistance(s,t),rel=t.alt-s.alt;if(d<11000&&Math.abs(rel)<1500&&!this.reported.has(t.id)){this.reported.set(t.id,now);this.lastWarn=now;const clock=((Math.round(angleDiff(geoBearing(s,t),s.heading)/30)+12)%12)||12,st=this.station(),nm=Math.max(1,Math.round(d/1852)),dir=['north','northeast','east','southeast','south','southwest','west','northwest'][Math.round(t.track/45)%8],type=t.type||'aircraft',alt=altText(Math.round(t.alt/100)*100,arr.country);
   this.atc(st.name,st.f,`${cs}, traffic ${clock} o'clock, ${nm} miles, ${dir}bound, ${type}, ${alt}.`,`${css}, traffic, ${clock} o'clock, ${nm} miles, ${dir}bound, ${type.split('').join(' ')}, ${altSpeech(Math.round(t.alt/100)*100,arr.country)}.`,.3,now);break;}}}
  for(const [k,t] of this.reported)if(now-t>600000)this.reported.delete(k);
  return this.log.slice(before);}
 private handoff(s:AtcSnap){const prev=this.station(),cs=this.callsign,css=this.cs();this.center=`${countryName(this.countryAt(s))} Control`;this.phase='enroute';this.lastHandoff={lat:s.lat,lon:s.lon};const f=this.freqs();
  this.atc(prev.name,prev.f,`${cs}, contact ${this.center} ${f.center}.`,`${css}, contact ${this.center} ${freqSpeech(f.center)}.`,.5,s.now);
  this.queue.push({at:s.now+6000,line:{who:'pilot',station:cs,freq:f.center,text:`${this.center}, ${cs}, ${altText(Math.round(s.alt/100)*100,this.dep.country)}.`,speech:`${this.center}, ${css}, ${altSpeech(Math.round(s.alt/100)*100,this.dep.country)}`}});
  this.queue.push({at:s.now+9500,line:{who:'atc',station:this.center,freq:f.center,text:`${cs}, ${this.center}, radar contact${this.assigned?`, maintain ${altText(this.assigned,this.dep.country)}`:''}.`,speech:`${css}, ${this.center}, radar contact${this.assigned?`, maintain ${altSpeech(this.assigned,this.dep.country)}`:''}.`}});}
 private countryAt(s:{lat:number;lon:number}){return geoDistance(s,this.dep)<geoDistance(s,this.arr)?this.dep.country:this.arr.country;}
}
