import { REALMS } from "./adventure";
export type StoryCue = "paper" | "bell" | "footsteps" | "shadow" | "dawn";
export type StoryBeat = { speaker: "The journey" | "Aoi" | "Ren" | "The keeper" | "The guardian"; text: string; focus: string; cue?: StoryCue };
const beat = (speaker: StoryBeat["speaker"], text: string, focus = "50% 50%", cue?: StoryCue): StoryBeat => ({ speaker, text, focus, cue });
const conversations: StoryBeat[][] = [
  [beat("Aoi", "The lantern used to reach every house. My grandmother never needed a candle to find her door.", "72% 55%"), beat("Ren", "Two lanterns on the keeper’s table. Gold for what we can touch. Blue for what we have forgotten.", "40% 45%", "paper"), beat("The keeper", "If you have come looking for the dawn, carry it together. One light will show the road. The other will show you why it matters.", "62% 40%", "bell")],
  [beat("Ren", "There. The silver fox. It keeps looking back at us.", "64% 40%", "footsteps"), beat("Aoi", "Then we give it a reason to trust us. I’ll wait whenever you need me.", "32% 65%"), beat("The journey", "Far below, the village is a scatter of unlit windows. The fox turns east. A thread of blue light follows its paws.", "76% 35%", "bell")],
  [beat("Aoi", "These roots are shaped like footsteps. Someone walked this way before us.", "30% 60%", "footsteps"), beat("Ren", "Raise the gold lantern. I can see a bridge where its shadow should be.", "62% 35%"), beat("The keeper", "A path remembers the people who made it. Walk gently. Leave it easier for the next traveler.", "50% 50%", "paper")],
  [beat("Ren", "A folded wish, behind the water. The ink has washed away except for one line.", "58% 45%", "paper"), beat("Aoi", "‘Let nobody make the long journey alone.’ Whoever wrote this was waiting for someone.", "34% 65%"), beat("The journey", "The paper is cold. The wish inside it is not. For a moment, both lanterns shine with the same light.", "66% 30%", "bell")],
  [beat("Aoi", "So many bright windows. Why is there nobody in the street?", "70% 45%"), beat("Ren", "Every house bought its own dawn. Maybe they forgot what a shared one felt like.", "30% 50%"), beat("The journey", "A shop door opens a finger’s width. Inside, an old merchant holds a letter he has been afraid to read.", "55% 60%", "paper")],
  [beat("The keeper", "I did not leave because I stopped loving the village. I left because something under it had learned to feed on our silence.", "40% 45%", "paper"), beat("Aoi", "She was trying to save the light. We’ve been following a rescue, not a theft.", "65% 60%"), beat("Ren", "Then we keep going. And when we return, we bring more than a lantern.", "50% 35%", "bell")],
  [beat("The journey", "The sea withdraws from the stones. A narrow road appears, then disappears beneath the next wave.", "68% 65%"), beat("Ren", "We could keep our lanterns. Find another place to live.", "35% 50%"), beat("Aoi", "And leave every door behind us dark? Watch the tide. We cross when we can cross together.", "60% 45%", "footsteps")],
  [beat("Aoi", "Two watchfires. One facing the sea, one facing the mountains.", "35% 40%", "bell"), beat("The keeper", "My brother watched the horizon. I watched for his fire. Neither of us ever called that keeping watch alone.", "68% 50%", "paper"), beat("Ren", "That’s what our lanterns are. A promise someone else can see.", "50% 35%")],
  [beat("Ren", "The snow covered every step she took. How do we know which way she went?", "30% 60%", "footsteps"), beat("Aoi", "We look for what she left for someone else. A shelter. A bell. A place to rest.", "70% 45%"), beat("The keeper", "Wisdom is not knowing every road. It is remembering who is walking beside you.", "50% 35%", "bell")],
  [beat("The keeper", "I hid the dawn from a hunger that had no face. It grew each time we said: this light is mine.", "45% 50%", "shadow"), beat("Aoi", "Were you afraid nobody would come?", "65% 55%"), beat("The keeper", "I was afraid someone would come alone. But there are two lights in the doorway.", "35% 40%", "bell")],
  [beat("Aoi", "My bridge ends in the middle. Yours begins on the other bank.", "35% 60%"), beat("Ren", "Then I repair your crossing, and you repair mine.", "70% 60%", "footsteps"), beat("The journey", "Neither traveler can build a way home for themselves. The river asks them to build it for each other.", "50% 40%", "bell")],
  [beat("The keeper", "We planted this tree for a person who had not yet arrived. No one asked which house its shade would belong to.", "65% 40%", "paper"), beat("Ren", "This is the village she remembers. Doors open. People listening.", "35% 60%"), beat("Aoi", "Then that’s the village we bring back.", "50% 35%", "bell")],
  [beat("The journey", "A thousand wishes hang above the water. None of them asks for the person who wrote it to be remembered.", "65% 35%"), beat("Ren", "The hunger gathered them like coins. It never understood what they were.", "32% 60%", "shadow"), beat("Aoi", "They’re ways home. Let’s give them back.", "50% 45%", "bell")],
  [beat("Aoi", "Our reflections. The gold and the blue are joining in the water.", "40% 65%"), beat("Ren", "The cavern isn’t opening for either lantern. It’s opening for both of us.", "70% 45%", "bell"), beat("The keeper", "Carry no light too tightly. A gift becomes smaller when you close your hand around it.", "50% 35%", "paper")],
  [beat("Ren", "Home. I can see the roof of my house. I thought it would feel warmer.", "65% 55%"), beat("The guardian", "If I keep every flame, I will never be cold again.", "40% 35%", "shadow"), beat("Aoi", "It sounds afraid. We don’t have to destroy it. We have to show it another way.", "50% 50%", "bell")],
  [beat("The guardian", "You carried the dawn this far. Which one of you will own it?", "50% 40%", "shadow"), beat("Aoi", "Neither of us.", "35% 60%"), beat("Ren", "Everyone waiting behind those doors. And everyone who hasn’t arrived yet.", "70% 60%"), beat("The journey", "For the first time, the guardian opens its hands. Beyond it, the great lantern is waiting.", "50% 30%", "dawn")],
];
export function storyFor(realm: number, ending = false): StoryBeat[] {
  if (ending) return [beat("The journey", "The first light does not come from the great lantern. It comes from a door opening beneath it.", "65% 55%", "dawn"), beat("Aoi", "Someone has set an extra place at the table.", "35% 65%"), beat("Ren", "For whoever comes next.", "70% 45%", "bell"), beat("The keeper", "You found the dawn. Now let the village learn how to keep giving it away.", "50% 35%", "paper"), beat("The journey", REALMS[15].epilogue, "50% 50%", "dawn")];
  return [beat("The journey", REALMS[realm].narrative, "50% 45%"), ...conversations[realm]];
}
