// Responsive propeller synthesis mixed with the existing credited wind recording.
// Engine sound is synthesized; this is not a recording of a real aircraft.
export class FlightAudio{
 private ctx:AudioContext;private gain:GainNode;private engine:OscillatorNode;private harmonic:OscillatorNode;private wind:HTMLAudioElement;private filter:BiquadFilterNode;private noise:AudioBufferSourceNode;private air:GainNode;private warning:OscillatorNode;private alarm:GainNode;
 constructor(){this.ctx=new AudioContext();this.gain=this.ctx.createGain();this.gain.gain.value=.025;this.filter=this.ctx.createBiquadFilter();this.filter.type='lowpass';this.filter.frequency.value=750;this.gain.connect(this.filter).connect(this.ctx.destination);this.engine=this.ctx.createOscillator();this.engine.type='sawtooth';this.engine.frequency.value=70;this.engine.connect(this.gain);this.engine.start();this.harmonic=this.ctx.createOscillator();this.harmonic.type='triangle';this.harmonic.frequency.value=140.8;const h=this.ctx.createGain();h.gain.value=.25;this.harmonic.connect(h).connect(this.gain);this.harmonic.start();
  const buffer=this.ctx.createBuffer(1,this.ctx.sampleRate*3,this.ctx.sampleRate),samples=buffer.getChannelData(0);let last=0;for(let i=0;i<samples.length;i++){last=.96*last+.04*(Math.random()*2-1);samples[i]=last*3;}this.noise=this.ctx.createBufferSource();this.noise.buffer=buffer;this.noise.loop=true;this.air=this.ctx.createGain();this.air.gain.value=0;const high=this.ctx.createBiquadFilter();high.type='highpass';high.frequency.value=200;this.noise.connect(high).connect(this.air).connect(this.ctx.destination);this.noise.start();this.warning=this.ctx.createOscillator();this.warning.frequency.value=850;this.alarm=this.ctx.createGain();this.alarm.gain.value=0;this.warning.connect(this.alarm).connect(this.ctx.destination);this.warning.start();
  this.wind=new Audio('/audio/wind-trees.mp3');this.wind.loop=true;this.wind.volume=.025;void this.wind.play().catch(()=>{});void this.ctx.resume();}
 update(throttle:number,speed:number,cockpit=false,stall=false,agl=1000){const now=this.ctx.currentTime,pulse=46+throttle*52+Math.sin(now*5)*.6;this.engine.frequency.setTargetAtTime(pulse,now,.25);this.harmonic.frequency.setTargetAtTime(pulse*2+.8,now,.25);this.gain.gain.setTargetAtTime((.012+throttle*.023)*(cockpit?.65:1),now,.2);this.filter.frequency.setTargetAtTime(cockpit?450:1100,now,.2);this.air.gain.setTargetAtTime(Math.min(.065,speed*.00065)*(cockpit?.28:1),now,.3);this.wind.volume=(cockpit?.006:.018)*Math.min(1,speed/30);this.alarm.gain.setTargetAtTime((stall||agl<35&&speed>40)?(Math.sin(now*9)>0?.015:0):0,now,.04);}
 cue(){const o=this.ctx.createOscillator(),g=this.ctx.createGain(),now=this.ctx.currentTime;o.frequency.setValueAtTime(620,now);o.frequency.exponentialRampToValueAtTime(920,now+.16);g.gain.setValueAtTime(.05,now);g.gain.exponentialRampToValueAtTime(.0001,now+.45);o.connect(g).connect(this.ctx.destination);o.start();o.stop(now+.45);}
 dispose(){this.engine.stop();this.harmonic.stop();this.noise.stop();this.warning.stop();void this.ctx.close();this.wind.pause();this.wind.src='';}
}
