// International Standard Atmosphere, real-weather decoding (METAR + model winds aloft) and runway selection.
export type WindLayer={alt:number;dir:number;speed:number};
export type CloudLayer={cover:'FEW'|'SCT'|'BKN'|'OVC';base:number;cb?:boolean};
export type Weather={source:string;station:string;metar:string;time:number;qnh:number;temp:number;dew:number;visibility:number;winds:WindLayer[];gust:number;clouds:CloudLayer[];precip:'none'|'rain'|'snow'|'thunder';intensity:number;turbulence:number;elevation:number};
export type WeatherPreset='live'|'clear'|'fair'|'cloudy'|'overcast'|'rain'|'storm'|'fog'|'snow'|'windy';
export const WEATHER_PRESETS:{id:WeatherPreset;label:string}[]=[{id:'live',label:'Live weather'},{id:'clear',label:'Clear skies'},{id:'fair',label:'Few clouds'},{id:'cloudy',label:'Scattered cumulus'},{id:'overcast',label:'Overcast'},{id:'rain',label:'Rain'},{id:'storm',label:'Thunderstorms'},{id:'fog',label:'Fog · low IFR'},{id:'snow',label:'Snow'},{id:'windy',label:'Strong wind'}];
const R=287.053,g=9.80665,L=.0065,ft=.3048;
export const COVER_OKTAS={FEW:2,SCT:4,BKN:6,OVC:8} as const;
/** Atmosphere at geometric altitude h (m) for a given surface temperature deviation and sea-level pressure. */
export function atmosphere(h:number,wx?:Pick<Weather,'qnh'|'temp'|'elevation'>){const dT=wx?wx.temp-(15-L*wx.elevation):0,p0=(wx?.qnh??1013.25)*100,T0=288.15+dT,hh=Math.max(-500,h),tropo=11000;
 let T:number,p:number;if(hh<=tropo){T=T0-L*hh;p=p0*Math.pow(T/T0,g/(R*L));}else{const Tt=T0-L*tropo,pt=p0*Math.pow(Tt/T0,g/(R*L));T=Tt;p=pt*Math.exp(-g*(hh-tropo)/(R*Tt));}
 return{T,p,rho:p/(R*T),a:Math.sqrt(1.4*R*T),sigma:p/(R*T)/1.225};}
/** Altimeter reading (m) for static pressure p (Pa) and the baro setting in hPa. */
export function altimeter(p:number,baro:number){return 288.15/L*(1-Math.pow(p/(baro*100),R*L/g));}
export function windAt(wx:Weather|null,h:number){if(!wx||!wx.winds.length)return{n:0,e:0,speed:0,dir:0};const w=wx.winds,agl=Math.max(0,h-wx.elevation);let dir:number,speed:number;
 if(h<=w[0].alt){const shear=agl<10?Math.max(.15,Math.log(Math.max(.4,agl)/.1)/Math.log(100)):1;dir=w[0].dir;speed=w[0].speed*shear;}
 else{let i=w.findIndex(l=>l.alt>h);if(i<0)i=w.length-1;const a=w[Math.max(0,i-1)],b=w[i],t=b.alt===a.alt?1:Math.min(1,Math.max(0,(h-a.alt)/(b.alt-a.alt))),d=((b.dir-a.dir+540)%360)-180;dir=(a.dir+d*t+360)%360;speed=a.speed+(b.speed-a.speed)*t;}
 const r=dir*Math.PI/180;return{n:-speed*Math.cos(r),e:-speed*Math.sin(r),speed,dir};}
const vis=(v:unknown)=>{const s=String(v??'10');const n=parseFloat(s);return Number.isFinite(n)?Math.min(50000,n*1609.34*(s.includes('+')?1.6:1)):16000;};
/** Combine a METAR (surface truth) with model winds aloft into one weather state. */
export function buildWeather(metar:any,model:any,elevation:number):Weather{const cur=model?.current,hr=model?.hourly;
 const winds:WindLayer[]=[];const sfcDir=Number(metar?.wdir),sfcSpd=Number(metar?.wspd)*.5144;
 winds.push({alt:elevation+10,dir:Number.isFinite(sfcDir)?sfcDir:Number(cur?.wind_direction_10m)||0,speed:Number.isFinite(sfcSpd)?sfcSpd:Number(cur?.wind_speed_10m)||0});
 for(const level of [850,700,500,300,250]){const z=Number(hr?.[`geopotential_height_${level}hPa`]?.[0]),d=Number(hr?.[`wind_direction_${level}hPa`]?.[0]),s=Number(hr?.[`wind_speed_${level}hPa`]?.[0]);if(Number.isFinite(z)&&Number.isFinite(d)&&Number.isFinite(s)&&z>winds[winds.length-1].alt+100)winds.push({alt:z,dir:d,speed:s});}
 let clouds:CloudLayer[]=[];if(metar&&Array.isArray(metar.clouds))clouds=metar.clouds.filter((c:any)=>c.cover in COVER_OKTAS&&Number.isFinite(c.base)).map((c:any)=>({cover:c.cover,base:elevation+c.base*ft,cb:String(metar.rawOb).includes(c.cover+String(Math.round(c.base/100)).padStart(3,'0')+'CB')}));
 if(!metar&&cur){const pick=(pct:number,base:number)=>{const c=pct<12?null:pct<38?'FEW':pct<62?'SCT':pct<88?'BKN':'OVC';if(c)clouds.push({cover:c,base:elevation+base});};pick(cur.cloud_cover_low,900);pick(cur.cloud_cover_mid,3200);pick(cur.cloud_cover_high,8000);}
 const code=Number(cur?.weather_code)||0,wxs=String(metar?.wxString??''),thunder=/TS/.test(wxs)||code>=95,snow=/SN|SG|PL/.test(wxs)||code>=71&&code<=77||code===85||code===86,rain=/RA|DZ|SH/.test(wxs)||code>=51&&code<=67||code>=80&&code<=82;
 const intensity=/\+/.test(wxs)||code===65||code===82||code>=96?1:/-/.test(wxs)||code===51||code===61||code===80?.35:.65,gust=Number(metar?.wgst)?Number(metar.wgst)*.5144:Number(cur?.wind_gusts_10m)||0;
 const qnh=Number(metar?.altim)>900?Number(metar.altim):Number(cur?.pressure_msl)||1013.25,temp=Number.isFinite(Number(metar?.temp))?Number(metar.temp):Number.isFinite(Number(cur?.temperature_2m))?Number(cur.temperature_2m):15;
 return{source:metar?`METAR ${metar.icaoId}`:model?'Open-Meteo model':'standard atmosphere',station:metar?.icaoId??'',metar:metar?.rawOb??'',time:Date.now(),qnh,temp,dew:Number(metar?.dewp??cur?.dew_point_2m??temp-5),visibility:metar?vis(metar.visib):Number(cur?.visibility)||20000,winds,gust,clouds:clouds.slice(0,4),precip:thunder?'thunder':snow?'snow':rain?'rain':'none',intensity,turbulence:Math.min(1,Math.max(0,(gust-winds[0].speed)/9)+(thunder?.6:0)+winds[0].speed/40),elevation};}
export function presetWeather(id:WeatherPreset,elevation:number,live?:Weather|null):Weather{if(id==='live'&&live)return live;const base:Weather={source:'Preset',station:'',metar:'',time:Date.now(),qnh:1013.25,temp:15-L*elevation,dew:8,visibility:40000,winds:[{alt:elevation+10,dir:270,speed:3},{alt:1500,dir:280,speed:9},{alt:3000,dir:285,speed:14},{alt:5600,dir:290,speed:22},{alt:9200,dir:290,speed:38},{alt:10400,dir:285,speed:42}],gust:0,clouds:[],precip:'none',intensity:0,turbulence:.05,elevation};const e=elevation;
 const P:Partial<Record<WeatherPreset,Partial<Weather>>>={clear:{},live:{},fair:{clouds:[{cover:'FEW',base:e+1200}],turbulence:.12},cloudy:{clouds:[{cover:'SCT',base:e+900},{cover:'FEW',base:e+3000}],turbulence:.2},overcast:{clouds:[{cover:'BKN',base:e+600},{cover:'OVC',base:e+1500}],visibility:12000,qnh:1006,turbulence:.15},rain:{clouds:[{cover:'BKN',base:e+400},{cover:'OVC',base:e+900}],visibility:4500,precip:'rain',intensity:.65,qnh:1002,gust:9,turbulence:.3,winds:[{alt:e+10,dir:200,speed:7},{alt:1500,dir:215,speed:15},{alt:3000,dir:230,speed:20},{alt:5600,dir:240,speed:28},{alt:9200,dir:250,speed:45}]},storm:{clouds:[{cover:'SCT',base:e+500,cb:true},{cover:'OVC',base:e+1400}],visibility:2500,precip:'thunder',intensity:1,qnh:996,gust:16,turbulence:.75,temp:24,winds:[{alt:e+10,dir:240,speed:10},{alt:1500,dir:250,speed:18},{alt:3000,dir:255,speed:24},{alt:5600,dir:260,speed:30},{alt:9200,dir:265,speed:48}]},fog:{clouds:[{cover:'OVC',base:e+60}],visibility:350,dew:12,temp:12,turbulence:0,winds:[{alt:e+10,dir:0,speed:0},{alt:600,dir:120,speed:3},{alt:3000,dir:250,speed:9}]},snow:{clouds:[{cover:'OVC',base:e+500}],visibility:2000,precip:'snow',intensity:.6,temp:-4,dew:-6,qnh:1009,turbulence:.15},windy:{clouds:[{cover:'FEW',base:e+1400}],gust:18,turbulence:.55,winds:[{alt:e+10,dir:310,speed:13},{alt:900,dir:315,speed:21},{alt:3000,dir:300,speed:30},{alt:5600,dir:295,speed:38},{alt:9200,dir:290,speed:55}]}};
 return{...base,...P[id],source:WEATHER_PRESETS.find(p=>p.id===id)?.label??'Preset'};}
export type RunwayEnd={ident:string;lat:number;lon:number;heading:number;length:number;width:number;endLat:number;endLon:number;estimated?:boolean;surface:string};
export function reciprocal(name:string){const m=/^(\d{1,2})([LRC]?)$/.exec(name.trim());if(!m)return name;const n=((Number(m[1])+17)%36)+1;return String(n).padStart(2,'0')+({L:'R',R:'L',C:'C'}[m[2]]??'');}
export function runwayEnds(runways:{name:string;length:number;width:number;surface:string;lat:number;lon:number;heading:number;endLat:number;endLon:number;estimated?:boolean}[]):RunwayEnd[]{return runways.flatMap(r=>{const base=r.name.split('/')[0];return[{ident:base.padStart(2,'0'),lat:r.lat,lon:r.lon,heading:r.heading,length:r.length,width:r.width,endLat:r.endLat,endLon:r.endLon,estimated:r.estimated,surface:r.surface},{ident:reciprocal(base),lat:r.endLat,lon:r.endLon,heading:(r.heading+180)%360,length:r.length,width:r.width,endLat:r.lat,endLon:r.lon,estimated:r.estimated,surface:r.surface}];});}
/** Pick the runway end with the strongest headwind; long runways win when winds are light. */
export function activeRunway(ends:RunwayEnd[],wx:Weather|null,preferLong=0){const w=wx?.winds[0];let best=ends[0],score=-Infinity;for(const e of ends){if(/^H/.test(e.ident))continue;const head=w?w.speed*Math.cos((w.dir-e.heading)*Math.PI/180):0,s=(w&&w.speed>2.5?head*4:0)+e.length/(preferLong?400:900)+(w&&w.speed<=2.5?Math.cos((e.heading-270)*Math.PI/180)*.3:0);if(s>score){score=s;best=e;}}return best;}
export function windComponents(wx:Weather|null,heading:number){const w=wx?.winds[0];if(!w)return{head:0,cross:0};const a=(w.dir-heading)*Math.PI/180;return{head:w.speed*Math.cos(a),cross:w.speed*Math.sin(a)};}
const PHONETIC='Alfa Bravo Charlie Delta Echo Foxtrot Golf Hotel India Juliett Kilo Lima Mike November Oscar Papa Quebec Romeo Sierra Tango Uniform Victor Whiskey X-ray Yankee Zulu'.split(' ');
export const phonetic=(letter:string)=>PHONETIC[letter.toUpperCase().charCodeAt(0)-65]??letter;
export function atisLetter(time:number){return PHONETIC[Math.floor(time/3600000)%26];}
export function describeClouds(wx:Weather){return wx.clouds.length?wx.clouds.map(c=>`${({FEW:'few',SCT:'scattered',BKN:'broken',OVC:'overcast'})[c.cover]} ${Math.round((c.base-wx.elevation)/ft/100)*100} feet${c.cb?' cumulonimbus':''}`).join(', '):'sky clear';}
export function windText(wx:Weather){const w=wx.winds[0],kt=Math.round(w.speed/.5144);return kt<2?'wind calm':`wind ${String(Math.round(w.dir/10)*10||360).padStart(3,'0')} at ${kt}${wx.gust>w.speed+4?` gusting ${Math.round(wx.gust/.5144)}`:''}`;}
export function atis(name:string,wx:Weather,runway:string,approach:string){const t=new Date(wx.time),z=`${String(t.getUTCHours()).padStart(2,'0')}${String(t.getUTCMinutes()).padStart(2,'0')}`,v=wx.visibility>=9999?'visibility 10 kilometers or more':wx.visibility<1500?`visibility ${Math.round(wx.visibility/50)*50} meters`:`visibility ${(wx.visibility/1000).toFixed(0)} kilometers`;
 return `${name} information ${atisLetter(wx.time)}, time ${z} Zulu. ${windText(wx)}, ${v}${wx.precip!=='none'?`, ${wx.intensity>.8?'heavy ':wx.intensity<.4?'light ':''}${wx.precip==='thunder'?'thunderstorm with rain':wx.precip}`:''}, ${describeClouds(wx)}. Temperature ${Math.round(wx.temp)}, dew point ${Math.round(wx.dew)}, Q N H ${Math.round(wx.qnh)}. Expect ${approach} runway ${runway}. Advise on initial contact you have information ${atisLetter(wx.time)}.`;}
