import {readFile} from 'node:fs/promises';
import {join} from 'node:path';
import {readRoom,insertRoom,saveRoom} from './roomStore';
import {GameError} from './game';
import {clamp} from './flight';
import {worldSpawn,geoDistance,geoMove,geoBearing,type Airport,type WorldPlane,type WorldRoom} from './worldFlight';
let catalog:Promise<Airport[]>|undefined;
export const airports=()=>catalog??=readFile(join(process.cwd(),'public/flight/global/airports.json'),'utf8').then(s=>JSON.parse(s) as Airport[]);
export async function airportSearch(query:string){const list=await airports(),q=query.trim().toLowerCase();return list.filter(a=>q?[a.id,a.iata,a.name,a.city,a.country].some(s=>s.toLowerCase().includes(q)):['RJTT','RJAA','RJOO','KJFK','KLAX','EGLL','LFPG','VABB','VEIM','YSSY'].includes(a.id)).sort((a,b)=>(a.id.toLowerCase()===q||a.iata.toLowerCase()===q?-1:0)-(b.id.toLowerCase()===q||b.iata.toLowerCase()===q?-1:0)||Number(b.type==='large_airport')-Number(a.type==='large_airport')).slice(0,25);}
type State=Omit<WorldRoom,'seat'|'version'>&{kind:'world';tokens:[string,string|null]};
function view(s:State,token:string,version:number){const {tokens,kind,...rest}=s,seat=tokens.indexOf(token);if(seat<0)throw new GameError('Join this flight to play.',403);return {...rest,seat,version} as WorldRoom;}
async function read(code:string){const row=await readRoom(`world:${code}`);if(!row)throw new GameError('World flight not found.',404);return row;}
export async function createWorld(name:string,departure:string,arrival:string){const list=await airports(),from=list.find(a=>a.id===departure),to=list.find(a=>a.id===arrival);if(!from||!to)throw new GameError('Choose an airport from the catalog.');const token=crypto.randomUUID(),alphabet='ABCDEFGHJKLMNPQRSTUVWXYZ23456789';for(let i=0;i<5;i++){const code=Array.from(crypto.getRandomValues(new Uint8Array(6)),n=>alphabet[n%alphabet.length]).join(''),s:State={kind:'world',code,names:[name.slice(0,18)||'Pilot',null],departure:from,arrival:to,planes:[worldSpawn(from),worldSpawn(from,1)],created:Date.now(),tokens:[token,null]};try{await insertRoom(`world:${code}`,JSON.stringify(s),Date.now());return{room:view(s,token,0),token};}catch(e){if(!/UNIQUE|duplicate/i.test(String(e)))throw e;}}throw new GameError('Cannot create flight.',503);}
export async function joinWorld(code:string,name:string){const row=await read(code),s=JSON.parse(row.state) as State;if(s.tokens[1])throw new GameError('Both seats are occupied. Resume with your original browser.',409);const token=crypto.randomUUID();s.tokens[1]=token;s.names[1]=name.slice(0,18)||'Pilot';if(!await saveRoom(`world:${code}`,JSON.stringify(s),row.version))throw new GameError('Another pilot joined first.',409);return{room:view(s,token,row.version+1),token};}
export async function worldAction(code:string,token:string,type:string,value?:WorldPlane){for(let attempt=0;attempt<8;attempt++){const row=await read(code),s=JSON.parse(row.state) as State,seat=s.tokens.indexOf(token);if(seat<0)throw new GameError('Join this flight to play.',403);if(type==='get')return view(s,token,row.version);const p=s.planes[seat];if(type==='recover')s.planes[seat]=worldSpawn(s.departure,seat,p.recovery+1);else if(type==='move'){const v=value;if(!v||!['lat','lon','alt','heading','pitch','roll','speed','throttle','flaps','fuel'].every(k=>Number.isFinite(v[k as keyof WorldPlane])))throw new GameError('Invalid flight position.');if(v.lat<-90||v.lat>90||v.lon<-180||v.lon>180)throw new GameError('Invalid geographic position.');const elapsed=clamp((Date.now()-p.seen)/1000,.05,2),distance=geoDistance(p,v),position=distance>elapsed*150+30?geoMove(p.lat,p.lon,geoBearing(p,v),elapsed*150+30):{lat:v.lat,lon:v.lon};s.planes[seat]={...p,...position,alt:clamp(v.alt,p.alt-elapsed*65-20,p.alt+elapsed*65+20),heading:(v.heading%360+360)%360,pitch:clamp(v.pitch,-.55,.55),roll:clamp(v.roll,-1.1,1.1),speed:clamp(v.speed,0,120),throttle:clamp(v.throttle,0,1),flaps:clamp(v.flaps,0,1),fuel:clamp(v.fuel,0,100),vertical:clamp(Number(v.vertical)||0,-90,90),engine:!!v.engine,gear:!!v.gear,ground:!!v.ground,airborne:!!v.airborne,distance:Math.max(p.distance,p.distance+Math.min(400,distance)),phase:String(v.phase).slice(0,40),seen:Date.now()};}else throw new GameError('Unknown action.');if(await saveRoom(`world:${code}`,JSON.stringify(s),row.version))return view(s,token,row.version+1);}throw new GameError('Flight connection busy.',409);}
