import {readFile} from 'node:fs/promises';
import {join} from 'node:path';
import {readRoom,insertRoom,saveRoom} from './roomStore';
import {GameError} from './game';
import {clamp} from './flight';
import {worldSpawn,geoDistance,geoMove,geoBearing,airportEnds,START_MODES,type Airport,type WorldPlane,type WorldRoom,type StartMode} from './worldFlight';
import {AIRCRAFT_IDS,type AircraftId} from './aircraft';
export type WorldOptions={aircraft?:string;start?:string;runway?:string;arrivalRunway?:string};
const craft=(v:unknown):AircraftId=>AIRCRAFT_IDS.includes(v as AircraftId)?v as AircraftId:'twin';
export async function nearbyAirports(lat:number,lon:number,km=60){const list=await airports();return list.filter(a=>Math.abs(a.lat-lat)<km/111&&a.type!=='heliport'&&a.type!=='balloonport'&&a.runways.length&&geoDistance(a,{lat,lon})<km*1000).sort((a,b)=>geoDistance(a,{lat,lon})-geoDistance(b,{lat,lon})).slice(0,40);}
let catalog:Promise<Airport[]>|undefined;
// Catalog headings are rounded; surveyed endpoints define the true centreline used for landing checks and the ILS.
export const airports=()=>catalog??=readFile(join(process.cwd(),'public/flight/global/airports.json'),'utf8').then(s=>{const list=JSON.parse(s) as Airport[];for(const a of list)for(const r of a.runways)if(!r.estimated&&geoDistance(r,{lat:r.endLat,lon:r.endLon})>100)r.heading=Math.round(geoBearing(r,{lat:r.endLat,lon:r.endLon})*10)/10;return list;});
export async function airportSearch(query:string){const list=await airports(),q=query.trim().toLowerCase();return list.filter(a=>q?[a.id,a.iata,a.name,a.city,a.country].some(s=>s.toLowerCase().includes(q)):['RJTT','RJAA','RJOO','KJFK','KLAX','EGLL','LFPG','VABB','VEIM','YSSY'].includes(a.id)).sort((a,b)=>(a.id.toLowerCase()===q||a.iata.toLowerCase()===q?-1:0)-(b.id.toLowerCase()===q||b.iata.toLowerCase()===q?-1:0)||Number(b.type==='large_airport')-Number(a.type==='large_airport')).slice(0,25);}
type State=Omit<WorldRoom,'seat'|'version'>&{kind:'world';tokens:[string,string|null]};
function view(s:State,token:string,version:number){const {tokens,kind,...rest}=s,seat=tokens.indexOf(token);if(seat<0)throw new GameError('Join this flight to play.',403);return {...rest,seat,version} as WorldRoom;}
async function read(code:string){const row=await readRoom(`world:${code}`);if(!row)throw new GameError('World flight not found.',404);return row;}
export async function createWorld(name:string,departure:string,arrival:string,o:WorldOptions={}){const list=await airports(),from=list.find(a=>a.id===departure),to=list.find(a=>a.id===arrival);if(!from||!to)throw new GameError('Choose an airport from the catalog.');const start:StartMode=START_MODES.some(m=>m.id===o.start)?o.start as StartMode:'runway',runway=airportEnds(from).find(e=>e.ident===o.runway)?.ident,arrivalRunway=airportEnds(to).find(e=>e.ident===o.arrivalRunway)?.ident,aircraft=craft(o.aircraft);const token=crypto.randomUUID(),alphabet='ABCDEFGHJKLMNPQRSTUVWXYZ23456789';for(let i=0;i<5;i++){const code=Array.from(crypto.getRandomValues(new Uint8Array(6)),n=>alphabet[n%alphabet.length]).join(''),s:State={kind:'world',code,names:[name.slice(0,18)||'Pilot',null],departure:from,arrival:to,planes:[worldSpawn(from,0,0,aircraft,start,runway,to,arrivalRunway),worldSpawn(from,1,0,aircraft,start==='cold'?'cold':'runway',runway)],created:Date.now(),tokens:[token,null],start,runway,arrivalRunway};try{await insertRoom(`world:${code}`,JSON.stringify(s),Date.now());return{room:view(s,token,0),token};}catch(e){if(!/UNIQUE|duplicate/i.test(String(e)))throw e;}}throw new GameError('Cannot create flight.',503);}
export async function joinWorld(code:string,name:string,aircraft?:string){const row=await read(code),s=JSON.parse(row.state) as State;if(s.tokens[1])throw new GameError('Both seats are occupied. Resume with your original browser.',409);const token=crypto.randomUUID();s.tokens[1]=token;s.names[1]=name.slice(0,18)||'Pilot';if(aircraft)s.planes[1]=worldSpawn(s.departure,1,0,craft(aircraft),s.start==='cold'?'cold':'runway',s.runway);if(!await saveRoom(`world:${code}`,JSON.stringify(s),row.version))throw new GameError('Another pilot joined first.',409);return{room:view(s,token,row.version+1),token};}
export async function worldAction(code:string,token:string,type:string,value?:WorldPlane){for(let attempt=0;attempt<8;attempt++){const row=await read(code),s=JSON.parse(row.state) as State,seat=s.tokens.indexOf(token);if(seat<0)throw new GameError('Join this flight to play.',403);if(type==='get')return view(s,token,row.version);const p=s.planes[seat];if(type==='recover')s.planes[seat]=worldSpawn(s.departure,seat,p.recovery+1,craft(p.aircraft),s.start==='cold'?'cold':'runway',s.runway);else if(type==='move'){const v=value;if(!v||!['lat','lon','alt','heading','pitch','roll','speed','throttle','flaps','fuel'].every(k=>Number.isFinite(v[k as keyof WorldPlane])))throw new GameError('Invalid flight position.');if(v.lat<-90||v.lat>90||v.lon<-180||v.lon>180)throw new GameError('Invalid geographic position.');const elapsed=clamp((Date.now()-p.seen)/1000,.05,2),distance=geoDistance(p,v),position=distance>elapsed*330+40?geoMove(p.lat,p.lon,geoBearing(p,v),elapsed*330+40):{lat:v.lat,lon:v.lon};s.planes[seat]={...p,...position,alt:clamp(v.alt,Math.max(-500,p.alt-elapsed*90-30),Math.min(15000,p.alt+elapsed*90+30)),heading:(v.heading%360+360)%360,pitch:clamp(v.pitch,-.55,.55),roll:clamp(v.roll,-1.1,1.1),speed:clamp(v.speed,0,330),throttle:clamp(v.throttle,0,1),flaps:clamp(v.flaps,0,1),fuel:clamp(v.fuel,0,100),vertical:clamp(Number(v.vertical)||0,-90,90),engine:!!v.engine,gear:!!v.gear,ground:!!v.ground,airborne:!!v.airborne,distance:Math.max(p.distance,p.distance+Math.min(400,distance)),phase:String(v.phase).slice(0,40),seen:Date.now(),aircraft:craft(p.aircraft),n1:clamp(Number(v.n1)||0,0,1.05),gearPos:clamp(Number(v.gearPos??(v.gear?1:0))||0,0,1),spoilers:clamp(Number(v.spoilers)||0,0,1),ias:clamp(Number(v.ias)||0,0,330),crashed:v.crashed?String(v.crashed).slice(0,40):undefined,law:undefined,vn:undefined,ve:undefined,vd:undefined,p:undefined,q:undefined,r:undefined};}else throw new GameError('Unknown action.');if(await saveRoom(`world:${code}`,JSON.stringify(s),row.version))return view(s,token,row.version+1);}throw new GameError('Flight connection busy.',409);}
